window.PDCA_DATA = {
  integration: {
    mode: "approval_scheduled_delivery_design",
    source: "web-admin-next.vercel.app",
    lastSyncedAt: "2026/04/28 20:49",
    message: "承認予約ワーカー設計へ更新済み",
  },
  reservationPolicy: {
    mode: "approval_scheduled_delivery",
    deliveryChannelDefault: "form",
    tabOpeningAutomation: "removed",
    currentBackendState: "ローカル予約ワーカーを追加。通常起動はドライランで、実送信は承認済み・時刻到達・フォーム配信・tracking_url・二重送信防止を満たす場合だけ実行できる設計。",
    requestedFlow: [
      "管理画面でグループ、テンプレート、キャンペーン、LP、送信件数を確認する",
      "ユーザーが確認OKを押し、配信日時と送信上限を保存する",
      "サーバー側の予約ワーカーが承認済み・scheduled_at到達済みのキャンペーンだけを実行する",
      "配信後にジョブログとトラッキングを取得し、PDCA管理画面へ集計値だけを反映する",
    ],
    approvedCampaignIds: [15, 16, 17, 18, 19, 20],
    defaultScheduleRule:
      "平日の日中を主軸に、まずは12時台で検証する。2026/04/29は祝日のため、現行6件の初期候補は2026/04/30(木) 12:00-12:25 JSTへ5分間隔で分散する。",
    defaultScheduleSlots: [
      "2026-04-30 12:00 JST / 新潟A / 制作進行",
      "2026-04-30 12:05 JST / 山口B / 品質安定",
      "2026-04-30 12:10 JST / 宮崎A / 制作進行",
      "2026-04-30 12:15 JST / 熊本B / 品質安定",
      "2026-04-30 12:20 JST / 福井A / 制作進行",
      "2026-04-30 12:25 JST / 山形B / 品質安定",
    ],
    futureTimeTests: [
      "平日12時台を基準にする",
      "母数が増えたら平日10時台・15時台も県別に分けて比較する",
      "夜間・休日はフォーム確認が後回しになりやすいため、初期検証では使わない",
    ],
    requiredGuards: [
      "承認済み判定",
      "配信日時とタイムゾーン",
      "delivery_channel=form",
      "送信上限",
      "二重送信防止キー",
      "停止条件",
      "監査ログ",
      "{{tracking_url}} とリダイレクト先LPの再検査",
      "送信者プロフィールの再確認",
    ],
    rule:
      "ユーザーから現行6キャンペーンは配信OKと確認済み。ただし外部企業への実送信はCodexでは行わず、本番では承認・日時・監査ログを持つ専用バックエンドが既存ツール側のキャンペーン配信を実行する。",
  },
  toolSchemaCheck: {
    checkedAt: "2026/04/28 20:49 JST",
    templateChannel:
      "既存ツールAPI上、テンプレートID7/8は channel=form。今後の作成スクリプトも channel=form を明示する。",
    groups:
      "グループID20-25は filter_scrape_status=null / filter_contact_status=null。グループ作成時にスクレイピング・コンタクト条件は設定しない方針と一致。",
    campaigns:
      "キャンペーンID15-20は draft で送信履歴なし。指定母数は152/123/104/95/108/80件。2026/04/28の予約ワーカードライランでは送信可能見込み70/56/55/49/36/35件、合計301件。",
    caveat:
      "既存ツールUIはAPIログインCookie注入で確認済み。キャンペーン詳細にはフォーム配信の送信実行フォーム、送信可能件数、送信間隔の説明が表示される。",
  },
  analysisContext: {
    target:
      "IT・サービスDBの広告・デザイン企業へ、東京・神奈川・大阪を温存したまま地方6県の別グループで広告・デザイン向けLPを並行配信し、送信成功数とクリック再現性を確認する",
    reason:
      "静岡A・長野Bは合計173件指定に対して送信成功58件、トラッキング補正クリック5社だった。クリックは出ているが母数不足のため、次回は業種やLPを変えず、地域だけを増やして判断材料を集める。",
    lpRule:
      "テンプレート本文に実URLを直書きせず、本文内のLP誘導は必ず {{tracking_url}} を使う。テンプレートのリダイレクト先LP URLは広告・デザイン向けLPにする。",
    contactToneRule:
      "AIコンサル以外の別商材でも同じ企業へ接点を持つ可能性があるため、文面は一商材一テーマに絞り、情報提供ベースで軽く案内する。強い売り込み、抽象的なAI活用、連続営業に見える表現は避ける。",
    trackingRule:
      "キャンペーン詳細へのクリック反映が遅れる、または反映されない場合は、トラッキングタブのクリック企業ID/企業名をジョブログの送信成功リストへ照合し、キャンペーン別の補正値を作る。公開管理画面には企業名やIDを出さず、集計値だけを表示する。",
    currentLpOptions: [
      "広告・デザイン向けLP: https://lp.ai-sabi.com/industries/it_service-advertising-design/",
      "システム開発向けLP: https://lp.ai-sabi.com/it-services-05/",
      "160業種LP: テンプレートごとにDB・大カテゴリ・詳細業種が一致するLPを選択",
    ],
    existingToolState: {
      groups: [
        "AI-SABI_広告デザイン_ITサービス_静岡県_A_20260427 / IT・サービス / 広告・デザイン / 静岡県 / グループID18",
        "AI-SABI_広告デザイン_ITサービス_長野県_B_20260427 / IT・サービス / 広告・デザイン / 長野県 / グループID19",
        "AI-SABI_広告デザイン_ITサービス_新潟県_A_20260427 / IT・サービス / 広告・デザイン / 新潟県 / グループID20",
        "AI-SABI_広告デザイン_ITサービス_山口県_B_20260427 / IT・サービス / 広告・デザイン / 山口県 / グループID21",
        "AI-SABI_広告デザイン_ITサービス_宮崎県_A_20260427 / IT・サービス / 広告・デザイン / 宮崎県 / グループID22",
        "AI-SABI_広告デザイン_ITサービス_熊本県_B_20260427 / IT・サービス / 広告・デザイン / 熊本県 / グループID23",
        "AI-SABI_広告デザイン_ITサービス_山形県_B_20260427 / IT・サービス / 広告・デザイン / 山形県 / グループID24",
        "AI-SABI_広告デザイン_ITサービス_福井県_A_20260427 / IT・サービス / 広告・デザイン / 福井県 / グループID25",
      ],
      templates: [
        "AI-SABI_Web制作_制作進行短縮_A_20260427 / テンプレートID7 / 広告・デザイン向けLP / {{tracking_url}} / 送信者プロフィール反映済み",
        "AI-SABI_Web制作_提案報告品質_B_20260427 / テンプレートID8 / 広告・デザイン向けLP / {{tracking_url}} / 送信者プロフィール反映済み",
        "WEB制作（テスト） / Web制作向けLP / 送信23件 / クリック0件",
      ],
      campaigns: [
        "AI-SABI_Web制作_広告デザイン_静岡県_制作進行_A_20260427 / キャンペーンID13 / 送信済み / 送信成功35件 / トラッキング補正3社",
        "AI-SABI_Web制作_広告デザイン_長野県_品質安定_B_20260427 / キャンペーンID14 / 送信済み / 送信成功23件 / トラッキング補正2社",
        "AI-SABI_Web制作_広告デザイン_新潟県_制作進行_A_20260427 / キャンペーンID15 / 承認済み / 予約日時未設定 / 推奨152件 / フォーム配信",
        "AI-SABI_Web制作_広告デザイン_山口県_品質安定_B_20260427 / キャンペーンID16 / 承認済み / 予約日時未設定 / 推奨123件 / フォーム配信",
        "AI-SABI_Web制作_広告デザイン_宮崎県_制作進行_A_20260427 / キャンペーンID17 / 承認済み / 予約日時未設定 / 推奨104件 / フォーム配信",
        "AI-SABI_Web制作_広告デザイン_熊本県_品質安定_B_20260427 / キャンペーンID18 / 承認済み / 予約日時未設定 / 推奨95件 / フォーム配信",
        "AI-SABI_Web制作_広告デザイン_山形県_品質安定_B_20260427 / キャンペーンID19 / 承認済み / 予約日時未設定 / 推奨108件 / フォーム配信",
        "AI-SABI_Web制作_広告デザイン_福井県_制作進行_A_20260427 / キャンペーンID20 / 承認済み / 予約日時未設定 / 推奨80件 / フォーム配信",
      ],
      lpStats: "it_service-advertising-design のLP閲覧5件、LINEクリック1件。LPイベントの企業IDは未紐づけのため、キャンペーン別LINEクリックは推定扱い。",
    },
  },
  nav: [
    { id: "dashboard", label: "ダッシュボード", icon: "dashboard" },
    { id: "ab-test", label: "ABテスト設計", icon: "ab" },
    { id: "approval", label: "配信管理", icon: "approval" },
    { id: "results", label: "結果分析", icon: "results" },
    { id: "templates", label: "テンプレート", icon: "template" },
    { id: "segments", label: "セグメント", icon: "segment" },
  ],
  approvalMetrics: [
    { label: "承認OK", value: "6", unit: "件", icon: "approval" },
    { label: "日時候補", value: "6", unit: "件", icon: "calendar" },
    { label: "配信チャネル", value: "form", unit: "", icon: "template" },
    { label: "次回指定母数", value: "662", unit: "件", icon: "campaign" },
    { label: "送信可能見込み", value: "301", unit: "件", icon: "results" },
  ],
  dashboard: {
    metrics: [
      { label: "前回指定件数", value: "173", unit: "件", trend: "静岡96 / 長野77", icon: "campaign" },
      { label: "前回送信成功", value: "58", unit: "件", trend: "成功率33.5%", icon: "approval" },
      { label: "補正クリック", value: "5", unit: "社", trend: "6クリック / 公開は集計のみ", icon: "results" },
      { label: "次回指定母数", value: "662", unit: "件", trend: "地方6県 / A336 B326", icon: "target" },
      { label: "送信可能見込み", value: "301", unit: "件", trend: "予約ワーカーの4/28再取得値", icon: "line" },
    ],
    pipeline: [
      { industry: "前回: Web制作 / 広告・デザイン", icon: "template", planning: 0, group: 2, template: 2, campaign: 2, waiting: 0, analyzing: 2 },
      { industry: "次回: 地方6県スケール", icon: "segment", planning: 0, group: 6, template: 2, campaign: 6, waiting: 6, analyzing: 0 },
      { industry: "次フェーズ: 大都市圏温存", icon: "database", planning: 1, group: 0, template: 0, campaign: 0, waiting: 0, analyzing: 0 },
    ],
    tasks: [
      {
        title: "承認OKと配信日時を保存する",
        detail:
          "新潟・山口・宮崎・熊本・山形・福井の別グループは承認OK。4/30(木)12時台を初期候補にし、管理画面で最終確認後に予約ワーカーからフォーム配信する設計にする。",
        priority: "高",
        due: "予約機能",
      },
      {
        title: "今回は業種とLPを変えない",
        detail:
          "クリックが出ているため、同じ広告・デザイン向けLPと同じA/B文面を継続し、地域だけを増やして再現性を見る。",
        priority: "高",
        due: "次回",
      },
      {
        title: "送信後はトラッキング補正で見る",
        detail:
          "キャンペーン詳細クリックが遅れる可能性があるため、トラッキングタブのクリック企業をジョブログへ照合して集計する。",
        priority: "高",
        due: "送信後",
      },
      {
        title: "次の分岐条件を決めておく",
        detail:
          "補正クリック率が3%以上なら大都市圏へ展開。1%未満なら同業種内の文面改善か、別業種LPテストへ切り替える。",
        priority: "中",
        due: "結果確認時",
      },
      {
        title: "公開画面に企業名・IDを出さない",
        detail:
          "クリック企業の特定は既存ツール内だけで行い、この画面には集計値だけを載せる。",
        priority: "中",
        due: "常時",
      },
    ],
    resultSummary: [
      { label: "前回送信成功", value: "58", unit: "件" },
      { label: "前回クリック企業", value: "5", unit: "社" },
      { label: "前回補正クリック率", value: "8.6", unit: "%" },
      { label: "次回指定母数", value: "662", unit: "件" },
      { label: "次回A指定", value: "336", unit: "件" },
      { label: "次回B指定", value: "326", unit: "件" },
    ],
    risks: [
      {
        title: "送信成功率が低い",
        detail:
          "前回は指定173件に対して送信成功58件。次回662件指定でも、実成功は200件前後に留まる可能性が高い。",
        action: "母数確保",
      },
      {
        title: "クリック集計の反映差",
        detail:
          "トラッキングタブではクリック企業が確認できる一方、キャンペーン詳細は0件のまま。現時点ではトラッキング補正値を正として扱う。",
        action: "補正集計",
      },
      {
        title: "A/Bの勝敗はまだ決めない",
        detail:
          "前回のA/Bはどちらもクリック率が近い。次回の地方6県で再現性を見てから、大都市圏投入パターンを決める。",
        action: "保留",
      },
    ],
  },
  abTests: [
    {
      id: "ab-web-scale-001",
      name: "Web制作_広告デザイン_地方6県スケール",
      industry: "広告・デザイン",
      hypothesis:
        "広告・デザイン会社には、AI一般論よりも制作進行と文章業務の負担を具体化した方が反応する。前回クリックが出たため、次回は同じ訴求で母数を増やして再現性を見る。",
      segment:
        "IT・サービスDB / 広告・デザイン / 新潟A・山口B・宮崎A・熊本B・山形B・福井A / スクレイピング・コンタクト条件なし",
      appealA: "制作進行の時短",
      appealB: "提案・報告文の品質安定",
      success: "送信成功率 / トラッキング補正クリック率 / LP閲覧 / LINEクリック",
      status: "送信待ち",
      subjectA: "{{company_name}}様へ、Web制作の提案文・進行連絡を整えるご案内",
      subjectB: "{{company_name}}様へ、提案・更新報告の品質を揃えるAI活用のご案内",
      introA:
        "制作そのもの以外に発生する提案文、要件整理、進行連絡、更新報告を軽くする切り口で初回接点を作る。",
      introB:
        "担当者ごとに表現や確認品質が変わりやすい提案・報告業務を安定させる切り口で初回接点を作る。",
      cta: "広告・デザイン向けLPの活用例を {{tracking_url}} で確認",
      bodyA: [
        "{{company_name}} 御中",
        "",
        "突然のご連絡失礼いたします。",
        "AI-SABI（twintrade合同会社）の仲西です。",
        "",
        "本日は、{{prefecture}}の広告・デザイン／Web制作会社様向けに、Web制作まわりの提案文、要件整理、進行連絡、更新報告を整えるAI活用について、情報提供としてご連絡しました。",
        "",
        "制作現場では、制作そのものに加えて、初回提案の文章化、修正内容の整理、顧客への進行共有などが日々積み重なりやすいかと思います。",
        "AI-SABIでは、いきなり大きなツール導入を行うのではなく、よく使う文章や確認項目を貴社の進め方に合わせて型化し、担当者の負担を少しずつ減らす形で伴走します。",
        "",
        "Web制作会社様向けの活用例を下記にまとめています。",
        "{{tracking_url}}",
        "",
        "提案文や進行連絡の整理に少しでもお役立ていただけそうでしたら、ご覧ください。",
        "",
        "どうぞよろしくお願いいたします。",
        "",
        "AI-SABI（twintrade合同会社）",
        "AI導入支援",
        "代表 仲西 匠",
      ].join("\n"),
      bodyB: [
        "{{company_name}} 御中",
        "",
        "突然のご連絡失礼いたします。",
        "AI-SABI（twintrade合同会社）の仲西です。",
        "",
        "本日は、{{prefecture}}で広告・デザイン領域の事業をされている企業様向けに、提案文や更新報告の品質を揃えるAI活用について、情報提供としてご連絡しました。",
        "",
        "Web制作やデザイン案件では、提案内容、進行報告、修正内容の伝え方が担当者ごとに変わりやすく、確認や手戻りの工数が増えることがあるかと思います。",
        "AI-SABIでは、貴社の言い回しや確認観点を整理し、AIで初稿作成と品質確認を行いやすい形に整えることで、少人数の体制でも提案・報告品質を揃えやすくする伴走を行います。",
        "",
        "Web制作会社様向けの活用例はこちらです。",
        "{{tracking_url}}",
        "",
        "提案文や更新報告の作成・確認に少しでもお役立ていただけそうでしたら、ご覧ください。",
        "",
        "どうぞよろしくお願いいたします。",
        "",
        "AI-SABI（twintrade合同会社）",
        "AI導入支援",
        "代表 仲西 匠",
      ].join("\n"),
      intent:
        "前回クリックが出たため、業種やLPを変えずに地方県だけを追加する。変数を増やしすぎず、次の判断を速くする。",
      reaction:
        "制作現場の文章業務に近いと感じ、広告・デザイン向けLPを確認する。",
      diff:
        "Aは制作進行短縮、Bは提案・報告品質。指定母数はA336件、B326件でほぼ均等にする。",
      improve:
        "補正クリック率が3%以上なら、勝ち筋ありとして東京・神奈川・大阪へ最適パターンを投入する。1%未満なら文面または業種LPを切り替える。",
    },
    {
      id: "ab-web-previous-001",
      name: "Web制作_広告デザイン_地方初回",
      industry: "広告・デザイン",
      hypothesis:
        "IT・ソフトウェア広めではなく、Web制作LPとの一致度が高い広告・デザイン企業へ対象を寄せると反応が出やすい",
      segment: "静岡A 96件指定→35件成功 / 長野B 77件指定→23件成功",
      appealA: "A: 制作進行の時短",
      appealB: "B: 提案・報告文の品質安定",
      success: "トラッキング補正クリック5社",
      status: "結果確認中",
      subjectA: "{{company_name}}様へ、Web制作の提案文・進行連絡を整えるご案内",
      subjectB: "{{company_name}}様へ、提案・更新報告の品質を揃えるAI活用のご案内",
      introA: "制作進行の文章業務を前面に出す。",
      introB: "提案・報告品質の安定を前面に出す。",
      cta: "{{tracking_url}} から詳細を確認",
      intent:
        "既存Web制作テストのクリック0件から、対象と文面を広告・デザイン向けに寄せた。",
      reaction:
        "クリックは出たが母数不足のため、次回は同じ軸で拡張する。",
      diff:
        "地域差が残るため勝敗ではなく反応有無の確認として扱う。",
      improve:
        "次回は地方6県に増やし、成功200件前後を狙う。",
    },
    {
      id: "ab-next-lane-001",
      name: "次フェーズ_業種LP切替候補",
      industry: "保留",
      hypothesis:
        "地方6県でクリック率が伸びない場合は、同じ広告・デザイン向け文面をいじるより、別業種LPまたは別詳細業種へ切り替える方が速い可能性がある",
      segment: "地方6県の結果確認後に決定",
      appealA: "広告・デザイン継続",
      appealB: "別業種LPへ切替",
      success: "補正クリック率 / LP閲覧 / LINEクリック",
      status: "保留",
      subjectA: "-",
      subjectB: "-",
      introA: "現行の勝ち筋が見えた場合のみ大都市圏へ展開。",
      introB: "クリック率が低い場合は別業種LPへ切り替える。",
      cta: "{{tracking_url}}",
      intent: "爆速PDCAの次の分岐を先に用意しておく。",
      reaction: "結果に応じて次アクションを迷わず切り替える。",
      diff: "今回は使わない。",
      improve: "地方6県配信後に判断する。",
    },
  ],
  approvals: [
    {
      id: "cp-scale-niigata-a",
      campaign: "AI-SABI_Web制作_広告デザイン_新潟県_制作進行_A_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_新潟県_A_20260427",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID15 / draft / グループID20 / テンプレートID7",
      target: 152,
      recommended: 152,
      sendableEstimate: 70,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "承認済み",
      userStatus: "予約候補",
      status: "承認済み",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:00 JST",
      priority: "高",
      intent: "A案の制作進行短縮訴求を新潟県で確認する。",
      conditions: "IT・サービスDB / 広告・デザイン / 新潟県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "既存ツール側の通常除外と送信時エラーに従う。送信前に重複・送信済みを確認する。",
      caution: "ユーザーから現行ドラフトは配信OKと確認済み。2026/04/30(木)12時台を初期候補にし、専用バックエンドが承認済み分だけフォーム配信する。",
    },
    {
      id: "cp-scale-yamaguchi-b",
      campaign: "AI-SABI_Web制作_広告デザイン_山口県_品質安定_B_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_山口県_B_20260427",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID16 / draft / グループID21 / テンプレートID8",
      target: 123,
      recommended: 123,
      sendableEstimate: 56,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "承認済み",
      userStatus: "予約候補",
      status: "承認済み",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:05 JST",
      priority: "高",
      intent: "B案の提案・報告品質安定訴求を山口県で確認する。",
      conditions: "IT・サービスDB / 広告・デザイン / 山口県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "既存ツール側の通常除外と送信時エラーに従う。送信前に重複・送信済みを確認する。",
      caution: "ユーザーから現行ドラフトは配信OKと確認済み。2026/04/30(木)12時台を初期候補にし、専用バックエンドが承認済み分だけフォーム配信する。",
    },
    {
      id: "cp-scale-miyazaki-a",
      campaign: "AI-SABI_Web制作_広告デザイン_宮崎県_制作進行_A_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_宮崎県_A_20260427",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID17 / draft / グループID22 / テンプレートID7",
      target: 104,
      recommended: 104,
      sendableEstimate: 55,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "承認済み",
      userStatus: "予約候補",
      status: "承認済み",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:10 JST",
      priority: "高",
      intent: "A案を九州地方でも確認し、新潟だけの地域差を避ける。",
      conditions: "IT・サービスDB / 広告・デザイン / 宮崎県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "既存ツール側の通常除外と送信時エラーに従う。送信前に重複・送信済みを確認する。",
      caution: "ユーザーから現行ドラフトは配信OKと確認済み。2026/04/30(木)12時台を初期候補にし、専用バックエンドが承認済み分だけフォーム配信する。",
    },
    {
      id: "cp-scale-kumamoto-b",
      campaign: "AI-SABI_Web制作_広告デザイン_熊本県_品質安定_B_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_熊本県_B_20260427",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID18 / draft / グループID23 / テンプレートID8",
      target: 95,
      recommended: 95,
      sendableEstimate: 49,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "承認済み",
      userStatus: "予約候補",
      status: "承認済み",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:15 JST",
      priority: "高",
      intent: "B案を九州地方でも確認し、山口だけの地域差を避ける。",
      conditions: "IT・サービスDB / 広告・デザイン / 熊本県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "既存ツール側の通常除外と送信時エラーに従う。送信前に重複・送信済みを確認する。",
      caution: "ユーザーから現行ドラフトは配信OKと確認済み。2026/04/30(木)12時台を初期候補にし、専用バックエンドが承認済み分だけフォーム配信する。",
    },
    {
      id: "cp-scale-yamagata-b",
      campaign: "AI-SABI_Web制作_広告デザイン_山形県_品質安定_B_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_山形県_B_20260427",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID19 / draft / グループID24 / テンプレートID8",
      target: 108,
      recommended: 108,
      sendableEstimate: 36,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "承認済み",
      userStatus: "予約候補",
      status: "承認済み",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:25 JST",
      priority: "高",
      intent: "4県だけでは母数不足のため追加し、B側の指定母数を補う。",
      conditions: "IT・サービスDB / 広告・デザイン / 山形県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "既存ツール側の通常除外と送信時エラーに従う。送信前に重複・送信済みを確認する。",
      caution: "ユーザーから現行ドラフトは配信OKと確認済み。2026/04/30(木)12時台を初期候補にし、専用バックエンドが承認済み分だけフォーム配信する。",
    },
    {
      id: "cp-scale-fukui-a",
      campaign: "AI-SABI_Web制作_広告デザイン_福井県_制作進行_A_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_福井県_A_20260427",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID20 / draft / グループID25 / テンプレートID7",
      target: 80,
      recommended: 80,
      sendableEstimate: 35,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "承認済み",
      userStatus: "予約候補",
      status: "承認済み",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:20 JST",
      priority: "高",
      intent: "A/B指定母数をほぼ均等にしつつ、地方県の追加検証を行う。",
      conditions: "IT・サービスDB / 広告・デザイン / 福井県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "既存ツール側の通常除外と送信時エラーに従う。送信前に重複・送信済みを確認する。",
      caution: "ユーザーから現行ドラフトは配信OKと確認済み。2026/04/30(木)12時台を初期候補にし、専用バックエンドが承認済み分だけフォーム配信する。",
    },
    {
      id: "cp-web-a",
      campaign: "AI-SABI_Web制作_広告デザイン_静岡県_制作進行_A_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_静岡県_A_20260427",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID13 / 送信済み / 送信成功35件 / トラッキング補正3社",
      target: 226,
      recommended: 96,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "結果確認中",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "配信済み",
      priority: "中",
      intent: "前回A案の結果保持。",
      conditions: "IT・サービスDB / 広告・デザイン / 静岡県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "送信成功35件、失敗50件、スキップ11件。",
      caution: "キャンペーン詳細側クリック0件のため、トラッキング補正で見る。",
    },
    {
      id: "cp-web-b",
      campaign: "AI-SABI_Web制作_広告デザイン_長野県_品質安定_B_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_長野県_B_20260427",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID14 / 送信済み / 送信成功23件 / トラッキング補正2社",
      target: 178,
      recommended: 77,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "結果確認中",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "配信済み",
      priority: "中",
      intent: "前回B案の結果保持。",
      conditions: "IT・サービスDB / 広告・デザイン / 長野県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "送信成功23件、失敗44件、スキップ10件。",
      caution: "キャンペーン詳細側クリック0件のため、トラッキング補正で見る。",
    },
  ],
  results: {
    metrics: [
      { label: "前回送信成功", value: "58", unit: "件", icon: "approval" },
      { label: "補正クリック企業", value: "5", unit: "社", icon: "results" },
      { label: "前回補正クリック率", value: "8.6", unit: "%", icon: "results" },
      { label: "次回指定母数", value: "662", unit: "件", icon: "target" },
      { label: "想定成功", value: "222", unit: "件", icon: "campaign" },
      { label: "大都市温存", value: "3", unit: "都府県", icon: "lock" },
    ],
    comparisons: [
      {
        test: "静岡A_制作進行",
        subject: "提案文・進行連絡",
        intro: "制作進行の文章業務",
        cta: "{{tracking_url}}",
        click: "3社 / 35件 = 8.6%",
        line: 0,
        decision: "有望 / 母数不足",
        next: "新潟・宮崎・福井でA案を追加確認",
      },
      {
        test: "長野B_品質安定",
        subject: "提案・更新報告",
        intro: "品質安定と確認工数",
        cta: "{{tracking_url}}",
        click: "2社 / 23件 = 8.7%",
        line: 1,
        decision: "有望 / 要確認",
        next: "山口・熊本・山形でB案を追加確認",
      },
      {
        test: "次回6県",
        subject: "同一文面・同一LP",
        intro: "地域だけ増やす",
        cta: "{{tracking_url}}",
        click: "未送信",
        line: "-",
        decision: "送信待ち",
        next: "送信後、トラッキング補正で翌日判定",
      },
    ],
    failures: [
      { label: "前回送信成功", value: 34 },
      { label: "前回失敗", value: 54 },
      { label: "前回スキップ", value: 12 },
      { label: "前回補正クリック率", value: 9 },
    ],
    improvements: [
      {
        title: "今回の判断",
        text:
          "業種やLPは変えず、地方県だけを増やす。クリックが出たばかりの段階で業種やLPまで変えると、何が効いたか判断しづらくなるため。",
      },
      {
        title: "次回作成済み",
        text:
          "新潟A、山口B、宮崎A、熊本B、山形B、福井Aの6キャンペーンをドラフト作成済み。合計指定母数は662件、前回成功率33.5%換算で送信成功222件前後を見込む。",
      },
      {
        title: "爆速PDCAの分岐",
        text:
          "補正クリック率が3%以上なら大都市圏へ展開。1%未満なら、文面を微修正するだけでなく、別業種LPや別カテゴリへの切替を検討する。",
      },
      {
        title: "集計で守ること",
        text:
          "キャンペーン詳細のクリック反映が遅れる場合は、トラッキングタブのクリック企業ID/企業名をジョブログへ照合する。公開管理画面には企業名やIDを出さない。",
      },
      {
        title: "停止すること",
        text:
          "東京・神奈川・大阪へ未検証パターンを投入すること、前回58件だけでA/B勝敗を決めること、キャンペーン詳細クリック0件だけで反応なしと判断することは避ける。",
      },
    ],
  },
  templates: [
    {
      name: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      industry: "広告・デザイン",
      appeal: "制作進行の時短",
      subject: "{{company_name}}様へ、Web制作の提案文・進行連絡を整えるご案内",
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      count: 35,
      click: "3社 / 8.6%",
      updated: "2026/04/27 地方6県で継続",
      label: "継続",
    },
    {
      name: "AI-SABI_Web制作_提案報告品質_B_20260427",
      industry: "広告・デザイン",
      appeal: "提案・報告文の品質安定",
      subject: "{{company_name}}様へ、提案・更新報告の品質を揃えるAI活用のご案内",
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      count: 23,
      click: "2社 / 8.7%",
      updated: "2026/04/27 地方6県で継続",
      label: "継続",
    },
    {
      name: "WEB制作（テスト）",
      industry: "IT・ソフトウェア",
      appeal: "Web制作業務のAI活用",
      subject: "Web制作業務のAI活用・業務改善について",
      lp: "Web制作向けLP",
      count: 23,
      click: "0%",
      updated: "2026/04/20",
      label: "見直し",
    },
    {
      name: "システム開発_候補",
      industry: "IT・ソフトウェア",
      appeal: "開発進行の整理",
      subject: "開発案件の要件整理・進行共有をAIで整えるご案内",
      lp: "システム開発向けLP / {{tracking_url}}",
      count: 0,
      click: "-",
      updated: "保留",
      label: "保留",
    },
  ],
  segments: [
    {
      name: "広告デザイン_ITサービス_静岡県_A",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "静岡県",
      estimated: 226,
      sendable: 35,
      excluded: "失敗50 / スキップ11 / クリック補正3社",
      order: "A配信済み",
      group: "作成済み / ID 18",
    },
    {
      name: "広告デザイン_ITサービス_長野県_B",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "長野県",
      estimated: 178,
      sendable: 23,
      excluded: "失敗44 / スキップ10 / クリック補正2社",
      order: "B配信済み",
      group: "作成済み / ID 19",
    },
    {
      name: "広告デザイン_ITサービス_新潟県_A",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "新潟県",
      estimated: 152,
      sendable: 51,
      excluded: "送信時に失敗・スキップ判定",
      order: "A送信待ち",
      group: "作成済み / ID 20",
    },
    {
      name: "広告デザイン_ITサービス_山口県_B",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "山口県",
      estimated: 123,
      sendable: 41,
      excluded: "送信時に失敗・スキップ判定",
      order: "B送信待ち",
      group: "作成済み / ID 21",
    },
    {
      name: "広告デザイン_ITサービス_宮崎県_A",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "宮崎県",
      estimated: 104,
      sendable: 35,
      excluded: "送信時に失敗・スキップ判定",
      order: "A送信待ち",
      group: "作成済み / ID 22",
    },
    {
      name: "広告デザイン_ITサービス_熊本県_B",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "熊本県",
      estimated: 95,
      sendable: 32,
      excluded: "送信時に失敗・スキップ判定",
      order: "B送信待ち",
      group: "作成済み / ID 23",
    },
    {
      name: "広告デザイン_ITサービス_山形県_B",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "山形県",
      estimated: 108,
      sendable: 36,
      excluded: "送信時に失敗・スキップ判定",
      order: "B送信待ち",
      group: "作成済み / ID 24",
    },
    {
      name: "広告デザイン_ITサービス_福井県_A",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "福井県",
      estimated: 80,
      sendable: 27,
      excluded: "送信時に失敗・スキップ判定",
      order: "A送信待ち",
      group: "作成済み / ID 25",
    },
    {
      name: "広告デザイン_東京神奈川大阪_温存",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "東京都・神奈川県・大阪府",
      estimated: 1381,
      sendable: 463,
      excluded: "地方6県の勝ち筋確認後に使用",
      order: "温存",
      group: "温存",
    },
    {
      name: "次フェーズ_別業種LP切替候補",
      db: "未定",
      industry: "未定",
      pref: "地方県優先",
      estimated: 0,
      sendable: 0,
      excluded: "地方6県の結果次第",
      order: "保留",
      group: "保留",
    },
  ],
};
