window.PDCA_DATA = {
  integration: {
    mode: "manual",
    source: "web-admin-next.vercel.app",
    lastSyncedAt: "2026/04/27 11:30",
    message: "AI分析はCodexへ貼るプロンプトを生成します",
  },
  analysisContext: {
    target: "Web制作向けLPを、IT・サービスDBの広告・デザイン企業へ小ロット配信する",
    reason:
      "既存のWeb制作テストはIT・ソフトウェアの鳥取県・徳島県で実施済みのため、次回は重複を避けて広告・デザインへ寄せる。",
    lpRule:
      "テンプレート本文に実URLを直書きせず、本文内のLP誘導は必ず {{tracking_url}} を使う。",
    contactToneRule:
      "今後、AIコンサル以外の別商材でも同じ企業へ接点を持つ可能性があるため、文面は一商材ごとに話題を絞り、情報提供ベースで軽く案内する。強い売り込み、抽象的なAI活用、連続営業に見える表現は避ける。",
    currentLpOptions: [
      "Web制作向けLP: https://lp.ai-sabi.com/it-services-02/",
      "システム開発向けLP: https://lp.ai-sabi.com/it-services-05/",
    ],
    existingToolState: {
      groups: [
        "WEB制作（テスト-徳島配信） / IT・ソフトウェア / 徳島県 / 64件",
        "WEB制作（テストー鳥取配信） / IT・ソフトウェア / 鳥取県 / 60件",
      ],
      templates: ["WEB制作（テスト） / Web制作向けLP / 送信23件 / クリック0件"],
      campaigns: [
        "WEB制作（テスト_徳島） / 対象64件 / 送信7件 / クリック0件 / 返信0件",
        "WEB制作（テスト_鳥取） / 対象60件 / 送信16件 / クリック0件 / 返信0件",
      ],
      lpStats: "it-services-02 のLP閲覧2件、LINEクリック0件",
    },
  },
  nav: [
    { id: "dashboard", label: "ダッシュボード", icon: "dashboard" },
    { id: "ab-test", label: "ABテスト設計", icon: "ab" },
    { id: "approval", label: "承認待ち", icon: "approval", badge: 2 },
    { id: "results", label: "結果分析", icon: "results" },
    { id: "templates", label: "テンプレート", icon: "template" },
    { id: "segments", label: "セグメント", icon: "segment" },
  ],
  dashboard: {
    metrics: [
      { label: "次回作成キャンペーン", value: "2", unit: "件", trend: "広告・デザイン向けA/B", icon: "template" },
      { label: "送信実行待ち", value: "0", unit: "件", trend: "作成前", icon: "campaign" },
      { label: "既存テスト", value: "2", unit: "件", trend: "鳥取・徳島は実施済み", icon: "ab" },
      { label: "既存クリック率", value: "0", unit: "%", trend: "送信23件 / クリック0件", icon: "results" },
      { label: "LINEクリック", value: "0", unit: "件", trend: "LP閲覧2件", icon: "line" },
    ],
    pipeline: [
      { industry: "Web制作 / 広告・デザイン", icon: "template", planning: 1, group: 0, template: 0, campaign: 0, waiting: 0, analyzing: 0 },
      { industry: "システム開発 / IT・ソフトウェア", icon: "database", planning: 0, group: 2, template: 1, campaign: 2, waiting: 0, analyzing: 2 },
      { industry: "LP選択肢拡張", icon: "sync", planning: 1, group: 0, template: 0, campaign: 0, waiting: 0, analyzing: 0 },
    ],
    tasks: [
      { title: "広告・デザイン向けA/B文面を確認", detail: "Aは制作進行短縮、Bは提案・報告品質の安定で比較", priority: "高", due: "今回" },
      { title: "鳥取A・徳島Bを15件ずつ作成", detail: "旧Pending、送信済み、フォーム不明、CAPTCHAを除外", priority: "高", due: "今回" },
      { title: "Web制作向けLPと {{tracking_url}} を設定", detail: "本文に実URLは直書きせず、LPはリダイレクト先LP URLで選択", priority: "高", due: "作成時" },
      { title: "別商材配信も見据えて文面を軽くする", detail: "今回はWeb制作まわりに絞った情報提供として書き、不要なら放念できる温度感にする", priority: "高", due: "作成時" },
      { title: "送信後は県差を考慮して判定", detail: "差が小さければ次回は同一県内で文面A/Bを再検証", priority: "中", due: "分析時" },
      { title: "Codex分析プロンプトを保存", detail: "AI分析はAPIではなく、この画面で生成してCodexへ貼り付ける", priority: "中", due: "随時" },
    ],
    resultSummary: [
      { label: "既存送信数", value: "23", unit: "件" },
      { label: "クリック率", value: "0", unit: "%" },
      { label: "LP閲覧", value: "2", unit: "件" },
      { label: "LINEクリック", value: "0", unit: "件" },
      { label: "返信", value: "0", unit: "件" },
    ],
    risks: [
      { title: "既存テストとの重複", detail: "IT・ソフトウェアの鳥取県・徳島県は既にテスト済みです。次回は広告・デザインへ寄せます。", action: "条件を確認" },
      { title: "クリック0件", detail: "既存Web制作テンプレートは23件送信でクリック0件のため、件名と冒頭の課題具体性を上げます。", action: "文面を見直す" },
      { title: "別商材との接触重複", detail: "今後、同じ企業へ別商材の案内を送る可能性があるため、初回から一商材一テーマの軽い情報提供にします。", action: "文面を抑える" },
    ],
  },
  abTests: [
    {
      id: "ab-web-001",
      name: "Web制作_広告デザイン_初回",
      industry: "広告・デザイン",
      hypothesis: "広告・デザイン会社には、AI一般論よりも制作進行と文章業務の負担を具体化した方が反応する",
      segment: "IT・サービスDB / 広告・デザイン / 鳥取県・徳島県 / pending",
      appealA: "制作進行の時短",
      appealB: "提案・報告文の品質安定",
      success: "クリック率 / LP閲覧 / LINEクリック",
      status: "承認待ち",
      subjectA: "{{company_name}}様へ、Web制作の提案文・進行連絡を整えるご案内",
      subjectB: "{{company_name}}様へ、提案・更新報告の品質を揃えるAI活用のご案内",
      introA: "制作そのもの以外に発生する提案文、要件整理、進行連絡、更新報告を軽くする切り口で初回接点を作る。",
      introB: "担当者ごとに表現や確認品質が変わりやすい提案・報告業務を安定させる切り口で初回接点を作る。",
      cta: "Web制作向けLPの活用例を {{tracking_url}} で確認",
      bodyA: [
        "{{company_name}} 御中",
        "",
        "突然のご連絡失礼いたします。",
        "AI-SABIの落合です。",
        "",
        "本日は、{{prefecture}}の広告・デザイン／Web制作会社様向けに、Web制作まわりの提案文、要件整理、進行連絡、更新報告を整えるAI活用について、情報提供としてご連絡しました。",
        "",
        "制作現場では、制作そのものに加えて、初回提案の文章化、修正内容の整理、顧客への進行共有などが日々積み重なりやすいかと思います。",
        "AI-SABIでは、いきなり大きなツール導入を行うのではなく、よく使う文章や確認項目を貴社の進め方に合わせて型化し、担当者の負担を少しずつ減らす形で伴走します。",
        "",
        "Web制作会社様向けの活用例を下記にまとめています。",
        "{{tracking_url}}",
        "",
        "今回はWeb制作まわりの文章・進行連絡に絞ったご案内です。",
        "ご関心に近い場合だけ、ご確認いただけますと幸いです。不要でしたらご放念ください。",
        "",
        "どうぞよろしくお願いいたします。",
        "",
        "AI-SABI",
        "落合",
      ].join("\n"),
      bodyB: [
        "{{company_name}} 御中",
        "",
        "突然のご連絡失礼いたします。",
        "AI-SABIの落合です。",
        "",
        "本日は、{{prefecture}}で広告・デザイン領域の事業をされている企業様向けに、提案文や更新報告の品質を揃えるAI活用について、情報提供としてご連絡しました。",
        "",
        "Web制作やデザイン案件では、提案内容、進行報告、修正内容の伝え方が担当者ごとに変わりやすく、確認や手戻りの工数が増えることがあるかと思います。",
        "AI-SABIでは、貴社の言い回しや確認観点を整理し、AIで初稿作成と品質確認を行いやすい形に整えることで、少人数の体制でも提案・報告品質を揃えやすくする伴走を行います。",
        "",
        "Web制作会社様向けの活用例はこちらです。",
        "{{tracking_url}}",
        "",
        "今回は提案文・更新報告の品質安定に絞ったご案内です。",
        "ご関心に近い場合だけ、ご確認いただけますと幸いです。不要でしたらご放念ください。",
        "",
        "どうぞよろしくお願いいたします。",
        "",
        "AI-SABI",
        "落合",
      ].join("\n"),
      intent: "既存のIT・ソフトウェア配信ではクリックが出ていないため、Web制作LPとの一致度が高い広告・デザイン企業へ対象を寄せる。",
      reaction: "制作現場の文章業務に近いと感じ、Web制作向けLPを確認する。",
      diff: "Aは制作進行と時短、Bは品質安定。県差が混ざるため、初回は方向性確認として扱う。",
      improve: "クリックが低ければ、件名冒頭に「提案文」「更新報告」をさらに前へ出す。別商材配信も見据え、次回以降も一商材一テーマの軽い情報提供にする。",
    },
    {
      id: "ab-web-002",
      name: "Web制作_広告デザイン_地域比較",
      industry: "広告・デザイン",
      hypothesis: "同じWeb制作訴求でも、地方小ロットの方が一斉営業感が弱く反応を見やすい",
      segment: "鳥取県A / 徳島県B / 送信15件ずつ",
      appealA: "鳥取県: 制作進行の時短",
      appealB: "徳島県: 提案・報告文の品質安定",
      success: "クリック率 / LP閲覧 / 送信成功率",
      status: "承認待ち",
      subjectA: "{{company_name}}様へ、Web制作の提案文・進行連絡を整えるご案内",
      subjectB: "{{company_name}}様へ、提案・更新報告の品質を揃えるAI活用のご案内",
      introA: "少人数の制作体制でも、提案文や進行連絡を無理なく整えるAI活用を情報提供として案内する。",
      introB: "担当者ごとの差が出やすい提案文・報告文を、現場に合わせて整える仕組みです。",
      cta: "{{tracking_url}} から詳細を確認",
      intent: "グループ分割機能が条件指定中心のため、まずは近い規模の県別セグメントでA/Bを作る。",
      reaction: "自社規模でも使えそうだと感じ、LPを確認する。",
      diff: "地域差ではなく、同程度の小ロットで文面差分を見るための暫定設計。",
      improve: "結果に差が出なければ、県ではなく詳細業種やフォーム品質で再分割する。",
    },
    {
      id: "ab-existing-001",
      name: "既存_Web制作_振り返り",
      industry: "IT・ソフトウェア",
      hypothesis: "IT・ソフトウェア広めの配信ではWeb制作LPとの一致度が弱く、クリックが出にくい",
      segment: "IT・ソフトウェア / 鳥取県・徳島県 / 送信済み23件",
      appealA: "Web制作業務のAI活用",
      appealB: "なし",
      success: "クリック率 / LP閲覧",
      status: "結果確認",
      subjectA: "Web制作業務のAI活用・業務改善について",
      subjectB: "-",
      introA: "既存テンプレートはWeb制作会社向けの文章業務・共有業務を訴求。",
      introB: "-",
      cta: "{{tracking_url}}",
      intent: "次回の対象変更と文面改善の根拠として、既存結果を残す。",
      reaction: "次回は対象と文面をWeb制作現場へより近づける。",
      diff: "既存はA/Bではなく単一テンプレートの結果確認。",
      improve: "広告・デザイン企業向けに、提案文・更新報告・制作進行の具体業務を前面に出す。",
    },
  ],
  approvals: [
    {
      id: "cp-web-a",
      campaign: "AI-SABI_Web制作_広告デザイン_鳥取_制作進行_A_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_鳥取_pending_20260427_A",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "未作成",
      target: 47,
      recommended: 15,
      lp: "Web制作向けLP / {{tracking_url}}",
      check: "OK",
      userStatus: "承認待ち",
      status: "作成準備",
      priority: "高",
      intent: "制作進行、提案文、進行連絡などWeb制作現場で発生しやすい文章業務を具体化し、Web制作向けLPのクリックにつなげる。",
      conditions: "IT・サービスDB / 広告・デザイン / 鳥取県 / contact_status=pending / scrape_status=done",
      exclusions: "既存IT・ソフトウェア配信条件、送信済み、旧Pending、フォーム不明、CAPTCHA",
      caution: "初回は15件まで。既存クリック0件のため、クリックが出なければ件名をさらに具体化する。別商材の案内も見据え、今回はWeb制作まわりの情報提供に絞る。",
    },
    {
      id: "cp-web-b",
      campaign: "AI-SABI_Web制作_広告デザイン_徳島_品質安定_B_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_徳島_pending_20260427_B",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "未作成",
      target: 52,
      recommended: 15,
      lp: "Web制作向けLP / {{tracking_url}}",
      check: "OK",
      userStatus: "承認待ち",
      status: "作成準備",
      priority: "高",
      intent: "提案文や更新報告の品質安定を切り口にし、制作会社の品質管理・確認工数の課題に寄せる。",
      conditions: "IT・サービスDB / 広告・デザイン / 徳島県 / contact_status=pending / scrape_status=done",
      exclusions: "既存IT・ソフトウェア配信条件、送信済み、旧Pending、フォーム不明、CAPTCHA",
      caution: "Aと同じ15件で比較。県差の影響があるため、勝敗ではなく方向性確認として扱う。別商材の案内も見据え、今回は提案・報告文の品質安定に絞る。",
    },
  ],
  results: {
    metrics: [
      { label: "既存送信成功", value: "23", unit: "件", icon: "approval" },
      { label: "クリック", value: "0", unit: "件", icon: "results" },
      { label: "クリック率", value: "0", unit: "%", icon: "results" },
      { label: "LP閲覧", value: "2", unit: "件", icon: "target" },
      { label: "LINEクリック", value: "0", unit: "件", icon: "line" },
      { label: "返信", value: "0", unit: "件", icon: "template" },
    ],
    comparisons: [
      { test: "WEB制作_鳥取", subject: "Web制作業務のAI活用", intro: "文章業務全般", cta: "LP確認", click: "0%", line: 0, decision: "見直し", next: "対象を広告・デザインへ変更し、制作業務名を前に出す" },
      { test: "WEB制作_徳島", subject: "Web制作業務のAI活用", intro: "文章業務全般", cta: "LP確認", click: "0%", line: 0, decision: "見直し", next: "同一LPで訴求を制作進行・提案文へ具体化する" },
      { test: "次回_Web制作", subject: "制作進行 vs 品質安定", intro: "広告・デザイン向け", cta: "{{tracking_url}}", click: "-", line: 0, decision: "承認待ち", next: "鳥取A・徳島Bを15件ずつ。県差があるため方向性確認として扱う" },
    ],
    failures: [
      { label: "クリックなし", value: 100 },
      { label: "LP閲覧のみ", value: 9 },
      { label: "LINEなし", value: 100 },
      { label: "返信なし", value: 100 },
    ],
    improvements: [
      { title: "結果の解釈", text: "既存Web制作テンプレートは送信23件でクリック0件。Web制作LPとの一致度が弱いIT・ソフトウェア広めの対象では反応が出にくい可能性が高い。" },
      { title: "文面で次回変えること", text: "件名と冒頭に、提案文、要件整理、進行連絡、更新報告などWeb制作現場の具体業務を入れる。" },
      { title: "対象で次回変えること", text: "IT・ソフトウェアではなく、Web制作LPと近い広告・デザイン企業へ寄せる。初回は鳥取県・徳島県の小ロットにする。" },
      { title: "LP導線で次回守ること", text: "テンプレート本文には実URLを直書きせず、必ず {{tracking_url}} を入れる。LP選択はWeb制作向けLPにする。" },
      { title: "別商材配信を見据えて守ること", text: "今後同じ企業へ別商材を案内する可能性があるため、今回の文面はWeb制作まわりの文章・進行連絡に絞り、情報提供ベースの軽い温度感にする。" },
      { title: "継続すること", text: "送信上限は15件ずつ、旧Pending除外、送信済み除外、フォーム品質確認を維持する。" },
      { title: "停止すること", text: "抽象的なAI活用だけの件名、IT全般に見える広い表現、システム開発寄りの訴求は今回使わない。" },
      { title: "今回の判断", text: "鳥取A・徳島Bの15件ずつで進めてよい。ただし県差が混ざるため、初回結果は勝敗ではなくクリック有無と訴求方向の確認として扱う。" },
    ],
  },
  templates: [
    { name: "WEB制作（テスト）", industry: "IT・ソフトウェア", appeal: "Web制作業務のAI活用", subject: "Web制作業務のAI活用・業務改善について", lp: "Web制作向けLP", count: 23, click: "0%", updated: "2026/04/20", label: "見直し" },
    { name: "AI-SABI_Web制作_制作進行短縮_A_20260427", industry: "広告・デザイン", appeal: "制作進行の時短", subject: "{{company_name}}様へ、Web制作の提案文・進行連絡を整えるご案内", lp: "Web制作向けLP / {{tracking_url}}", count: 0, click: "-", updated: "承認待ち", label: "承認待ち" },
    { name: "AI-SABI_Web制作_提案報告品質_B_20260427", industry: "広告・デザイン", appeal: "提案・報告文の品質安定", subject: "{{company_name}}様へ、提案・更新報告の品質を揃えるAI活用のご案内", lp: "Web制作向けLP / {{tracking_url}}", count: 0, click: "-", updated: "承認待ち", label: "承認待ち" },
    { name: "システム開発_候補", industry: "IT・ソフトウェア", appeal: "開発進行の整理", subject: "開発案件の要件整理・進行共有をAIで整えるご案内", lp: "システム開発向けLP / {{tracking_url}}", count: 0, click: "-", updated: "保留", label: "保留" },
  ],
  segments: [
    { name: "広告デザイン_鳥取_pending", db: "IT・サービス", industry: "広告・デザイン", pref: "鳥取県", estimated: 47, sendable: 24, excluded: "フォーム不明 / CAPTCHA / 送信済み", order: "1位", group: "作成予定" },
    { name: "広告デザイン_徳島_pending", db: "IT・サービス", industry: "広告・デザイン", pref: "徳島県", estimated: 52, sendable: 19, excluded: "フォーム不明 / CAPTCHA / 送信済み", order: "2位", group: "作成予定" },
    { name: "広告デザイン_福井_pending", db: "IT・サービス", industry: "広告・デザイン", pref: "福井県", estimated: 80, sendable: 35, excluded: "フォーム不明 / CAPTCHA / 送信済み", order: "3位", group: "候補" },
    { name: "広告デザイン_島根_pending", db: "IT・サービス", industry: "広告・デザイン", pref: "島根県", estimated: 76, sendable: 30, excluded: "フォーム不明 / CAPTCHA / 送信済み", order: "4位", group: "候補" },
    { name: "広告デザイン_山形_pending", db: "IT・サービス", industry: "広告・デザイン", pref: "山形県", estimated: 108, sendable: 36, excluded: "フォーム不明 / CAPTCHA / 送信済み", order: "5位", group: "候補" },
  ],
};
