window.PDCA_DATA = {
  integration: {
    mode: "tool_side_scheduled_delivery_results_and_schedules",
    source: "web-admin-next.vercel.app",
    lastSyncedAt: "2026/05/02 12:36",
    message: "5/2昼時点の休日初速と5/3・5/4フォーム予約済み状態を反映",
  },
  reservationPolicy: {
    mode: "tool_side_scheduled_delivery",
    deliveryChannelDefault: "form",
    tabOpeningAutomation: "removed",
    currentBackendState: "4/30の地方6県配信はローカル予約ワーカーで完了済み。既存ツール側に日時予約機能が実装されたため、今後の予約配信はツール側の「実行タイミング: 日時を予約」を正とし、ローカルWindowsタスクは二重送信防止のため停止済み。",
    requestedFlow: [
      "既存ツールでグループ、テンプレート、キャンペーン、LP、送信件数を確認する",
      "キャンペーン詳細の実行タイミングで「日時を予約」を選び、ツール側へ予約日時と送信件数を保存する",
      "ツール側の予約機能が指定時刻にフォーム配信を処理する",
      "配信後にジョブログとトラッキングを取得し、PDCA管理画面へ集計値だけを反映する",
    ],
    approvedCampaignIds: [15, 16, 17, 18, 19, 20, 30, 31, 32, 33, 34, 35, 37, 38, 39, 40, 41, 42, 45, 46, 47, 48],
    draftCampaignIds: [36, 43, 44],
    defaultScheduleRule:
      "今後はツール側予約を使う。5/1のフォーム主配信と5/2休日検証A/Bは配信済み/集計中。ユーザー承認により5/3-5/4休日継続A厚め/B少量、5/7-5/8平日C/Dはツール側予約済み。5/8-5/11メール補完はフォーム結果確認後に扱うため下書きのまま維持する。",
    defaultScheduleSlots: [
      "2026-05-01 13:05 JST / W1 A / 北海道・茨城・徳島",
      "2026-05-01 13:15 JST / W1 B / 愛知",
      "2026-05-01 13:25 JST / W2 A / 埼玉・三重・秋田",
      "2026-05-01 13:35 JST / W2 B / 兵庫・鳥取",
      "2026-05-01 13:45 JST / W3 A / 千葉・福岡・群馬",
      "2026-05-01 13:55 JST / W3 B / 沖縄・京都",
    ],
    nextDraftScheduleSlots: [
      "2026-05-02 11:00/11:15 JST / 休日A/B検証 / キャンペーンID37-38 / 予約済み",
      "2026-05-03 11:00/11:15 JST / 休日継続A厚め・B少量 / キャンペーンID45-46 / 予約済み",
      "2026-05-04 11:00/11:15 JST / 休日継続A厚め・B少量 / キャンペーンID47-48 / 予約済み",
      "2026-05-07 11:00/11:15 JST / C短縮CTA・D LINE相談導線 / キャンペーンID39-40 / 予約済み",
      "2026-05-08 11:00/11:15 JST / C短縮CTA・D LINE相談導線追加 / キャンペーンID41-42 / 予約済み",
      "2026-05-08 14:00 JST候補 / 5/1未達メール補完92件 / キャンペーンID43 / 下書き",
      "2026-05-11 11:00 JST候補 / 5/1未達メール補完74件 / キャンペーンID44 / 下書き",
    ],
    futureTimeTests: [
      "平日12時台を基準にする",
      "母数を増やす場合は平日10時台・12時台・15時台で県別に分けて比較する",
      "メール補完はフォーム配信と同時に予約せず、ジョブログ反映後の翌営業日以降に1日100件以内で分割する",
      "休日は伸びにくい前提を検証するため、5/2に既存A/Bを実施。5/2昼時点ではAの初速が強いため、5/3-5/4はA厚め/B少量で予約済み。平日C/Dと混ぜて勝敗判断せず、曜日差の参考値として扱う",
    ],
    requiredGuards: [
      "承認済み判定",
      "配信日時とタイムゾーン",
      "delivery_channel=form",
      "送信上限",
      "二重送信防止キー",
      "停止条件",
      "監査ログ",
      "{{tracking_url}} とリダイレクト先LPの再検査",
      "送信者プロフィールの再確認",
      "フォーム配信とメール補完を同時刻に重ねない",
    ],
    rule:
      "4/30の承認済み6キャンペーンは配信完了。今後の予約配信は既存ツール側の予約機能を使用し、ローカル予約ワーカーは運用停止する。Codexは結果集計、次回案、グループ・テンプレート・キャンペーン作成までを担当し、外部企業への送信操作はユーザー承認済みのツール側予約に寄せる。",
  },
  toolSchemaCheck: {
    checkedAt: "2026/05/02 12:36 JST",
    templateChannel:
      "既存ツールAPI上、テンプレートID7/8は channel=form。今後の作成スクリプトも channel=form を明示する。",
    groups:
      "新グループ作成UIを確認済み。IT・サービスDB / 広告・デザインは選択可能。フォーム主配信はフォーム送信状態「未送信」を正とし、メール送信状態・メール保有では絞らない。メール補完ではフォーム送信状態「失敗 + スキップ全部」、メール保有「メールあり」、メール送信状態「未送信」を正とする。",
    campaigns:
      "キャンペーンID15-20は2026/04/30 12時台に配信完了。キャンペーンID30-35は2026/05/01 13:05-13:55 JSTのツール側予約で配信完了。キャンペーンID37-38は2026/05/02に配信完了/集計中。キャンペーンID45-48は2026/05/03-05/04の休日継続枠として予約済み。キャンペーンID39-42は2026/05/07-05/08の平日C/Dとして予約済み。メール補完キャンペーンID36/43/44は下書きのまま未予約。",
    caveat:
      "キャンペーン詳細側のクリックは0件のままのため、クリック補正は `/api/tracking/clicks` のリアルタイムクリック一覧を正とする。`/api/tracking/lp-stats` では広告・デザインLPのPVとLINEクリックも確認する。",
  },
  analysisContext: {
    target:
      "IT・サービスDBの広告・デザイン企業へ、2026/05/01 13時台に6キャンペーンを配信した。総対象3,082件のうち、ジョブ処理済み1,301件、送信成功432件、トラッキング補正ユニーククリック21社、広告・デザインLPのLINEクリック4件が出ている。2026/05/02昼時点の休日A/Bは送信成功126件、補正ユニーククリック7社、成功ベース5.6%。Aは5社/57成功=8.8%、Bは2社/69成功=2.9%のため、5/3・5/4はA厚め/B少量で追加予約済み。",
    reason:
      "5/1は成功432件に対してユニーククリック21社で成功ベース4.9%。累計では成功594件、ユニーククリック32社で5.4%。5/2昼時点では休日でも反応が出ており、Aの初速が強い。休日の最終判断は夜時点で再確認するが、毎日確認できない前提で2日先までA厚め/B少量の予約を入れ、検証できたタイミングで予約済み内容も更新する。",
    lpRule:
      "テンプレート本文に実URLを直書きせず、本文内のLP誘導は必ず {{tracking_url}} を使う。テンプレートのリダイレクト先LP URLは広告・デザイン向けLPにする。",
    contactToneRule:
      "AIコンサル以外の別商材でも同じ企業へ接点を持つ可能性があるため、文面は一商材一テーマに絞り、情報提供ベースで軽く案内する。強い売り込み、抽象的なAI活用、連続営業に見える表現は避ける。",
    trackingRule:
      "キャンペーン詳細へのクリック反映が遅れる、または反映されない場合は、トラッキングタブのクリック企業ID/企業名をジョブログの送信成功リストへ照合し、キャンペーン別の補正値を作る。公開管理画面には企業名やIDを出さず、集計値だけを表示する。",
    currentLpOptions: [
      "広告・デザイン向けLP: https://lp.ai-sabi.com/industries/it_service-advertising-design/",
      "システム開発向けLP: https://lp.ai-sabi.com/it-services-05/",
      "160業種LP: テンプレートごとにDB・大カテゴリ・詳細業種が一致するLPを選択",
    ],
    existingToolState: {
      groups: [
        "AI-SABI_広告デザイン_ITサービス_静岡県_A_20260427 / IT・サービス / 広告・デザイン / 静岡県 / グループID18",
        "AI-SABI_広告デザイン_ITサービス_長野県_B_20260427 / IT・サービス / 広告・デザイン / 長野県 / グループID19",
        "AI-SABI_広告デザイン_ITサービス_新潟県_A_20260427 / IT・サービス / 広告・デザイン / 新潟県 / グループID20",
        "AI-SABI_広告デザイン_ITサービス_山口県_B_20260427 / IT・サービス / 広告・デザイン / 山口県 / グループID21",
        "AI-SABI_広告デザイン_ITサービス_宮崎県_A_20260427 / IT・サービス / 広告・デザイン / 宮崎県 / グループID22",
        "AI-SABI_広告デザイン_ITサービス_熊本県_B_20260427 / IT・サービス / 広告・デザイン / 熊本県 / グループID23",
        "AI-SABI_広告デザイン_ITサービス_山形県_B_20260427 / IT・サービス / 広告・デザイン / 山形県 / グループID24",
        "AI-SABI_広告デザイン_ITサービス_福井県_A_20260427 / IT・サービス / 広告・デザイン / 福井県 / グループID25",
        "AI-SABI_広告デザイン_ITサービス_W1_A_未送信_20260507 / 北海道・茨城県・徳島県 / グループID32 / 対象652件 / フォーム送信可能298件",
        "AI-SABI_広告デザイン_ITサービス_W1_B_未送信_20260507 / 愛知県 / グループID33 / 対象389件 / フォーム送信可能162件",
        "AI-SABI_広告デザイン_ITサービス_W2_A_未送信_20260507 / 埼玉県・三重県・秋田県 / グループID34 / 対象660件 / フォーム送信可能261件",
        "AI-SABI_広告デザイン_ITサービス_W2_B_未送信_20260507 / 兵庫県・鳥取県 / グループID35 / 対象368件 / フォーム送信可能160件",
        "AI-SABI_広告デザイン_ITサービス_W3_A_未送信_20260507 / 千葉県・福岡県・群馬県 / グループID36 / 対象660件 / フォーム送信可能278件",
        "AI-SABI_広告デザイン_ITサービス_W3_B_未送信_20260507 / 沖縄県・京都府 / グループID37 / 対象353件 / フォーム送信可能142件",
        "AI-SABI_広告デザイン_ITサービス_フォーム未達メール補完_20260507 / グループID38 / 4/30未達分 / フォーム失敗+スキップ全部・メールあり・メール未送信 / 対象70件",
        "AI-SABI_広告デザイン_ITサービス_休日検証_A_未送信_20260502 / 栃木県・岐阜県・石川県・高知県・佐賀県 / グループID39 / 対象549件 / 予約済み",
        "AI-SABI_広告デザイン_ITサービス_休日検証_B_未送信_20260502 / 宮城県・福島県・富山県・山梨県・香川県 / グループID40 / 対象501件 / 予約済み",
        "AI-SABI_広告デザイン_ITサービス_短縮CTA_C_未送信_20260507 / 東京都・神奈川県 / グループID41 / 対象994件 / 予約済み",
        "AI-SABI_広告デザイン_ITサービス_LINE相談導線_D_未送信_20260507 / 大阪府・兵庫県・奈良県・和歌山県・京都府 / グループID42 / 対象813件 / 予約済み",
        "AI-SABI_広告デザイン_ITサービス_短縮CTA_C_未送信_20260508 / 北海道・愛知県・静岡県・長野県・青森県・岩手県 / グループID43 / 対象863件 / 予約済み",
        "AI-SABI_広告デザイン_ITサービス_LINE相談導線_D_未送信_20260508 / 埼玉県・千葉県・福岡県・沖縄県・鹿児島県・大分県 / グループID44 / 対象819件 / 予約済み",
        "AI-SABI_広告デザイン_ITサービス_フォーム未達メール補完_5月1日分_1_20260508 / グループID45 / 5/1未達92件 / メールあり・メール未送信 / 下書き",
        "AI-SABI_広告デザイン_ITサービス_フォーム未達メール補完_5月1日分_2_20260511 / グループID46 / 5/1未達74件 / メールあり・メール未送信 / 下書き",
        "AI-SABI_広告デザイン_ITサービス_休日継続_A_未送信_20260503 / 栃木県・岐阜県・石川県・高知県・佐賀県・岡山県・広島県・愛媛県 / グループID47 / 対象690件 / 予約済み",
        "AI-SABI_広告デザイン_ITサービス_休日継続_B_未送信_20260503 / 宮城県・福島県・富山県・山梨県・香川県・島根県・長崎県 / グループID48 / 対象476件 / 予約済み",
        "AI-SABI_広告デザイン_ITサービス_休日継続_A_未送信_20260504 / 新潟県・宮崎県・福井県・茨城県・徳島県・三重県・秋田県・群馬県・滋賀県 / グループID49 / 対象729件 / 予約済み",
        "AI-SABI_広告デザイン_ITサービス_休日継続_B_未送信_20260504 / 山口県・熊本県・山形県・鳥取県 / グループID50 / 対象208件 / 予約済み",
      ],
      templates: [
        "AI-SABI_Web制作_制作進行短縮_A_20260427 / テンプレートID7 / 広告・デザイン向けLP / {{tracking_url}} / 送信者プロフィール反映済み",
        "AI-SABI_Web制作_提案報告品質_B_20260427 / テンプレートID8 / 広告・デザイン向けLP / {{tracking_url}} / 送信者プロフィール反映済み",
        "AI-SABI_Web制作_フォーム未達メール補完_20260507 / テンプレートID12 / channel=email / メール本文内に署名を明記",
        "AI-SABI_Web制作_短縮CTA_C_20260507 / テンプレートID13 / channel=form / 短縮CTA新比較軸",
        "AI-SABI_Web制作_LINE相談導線_D_20260507 / テンプレートID14 / channel=form / LINE相談導線新比較軸",
        "WEB制作（テスト） / Web制作向けLP / 送信23件 / クリック0件",
      ],
      campaigns: [
        "AI-SABI_Web制作_広告デザイン_静岡県_制作進行_A_20260427 / キャンペーンID13 / 送信済み / 送信成功35件 / トラッキング補正3社",
        "AI-SABI_Web制作_広告デザイン_長野県_品質安定_B_20260427 / キャンペーンID14 / 送信済み / 送信成功23件 / トラッキング補正2社",
        "AI-SABI_Web制作_広告デザイン_新潟県_制作進行_A_20260427 / キャンペーンID15 / 送信成功26件 / 失敗32件 / スキップ12件 / 補正クリック1社",
        "AI-SABI_Web制作_広告デザイン_山口県_品質安定_B_20260427 / キャンペーンID16 / 送信成功16件 / 失敗30件 / スキップ10件 / 補正クリック1社",
        "AI-SABI_Web制作_広告デザイン_宮崎県_制作進行_A_20260427 / キャンペーンID17 / 送信成功16件 / 失敗27件 / スキップ12件 / 補正クリック0社",
        "AI-SABI_Web制作_広告デザイン_熊本県_品質安定_B_20260427 / キャンペーンID18 / 送信成功17件 / 失敗27件 / スキップ5件 / 補正クリック0社",
        "AI-SABI_Web制作_広告デザイン_山形県_品質安定_B_20260427 / キャンペーンID19 / 送信成功14件 / 失敗16件 / スキップ6件 / 補正クリック0社",
        "AI-SABI_Web制作_広告デザイン_福井県_制作進行_A_20260427 / キャンペーンID20 / 送信成功15件 / 失敗17件 / スキップ3件 / 補正クリック3社",
        "AI-SABI_Web制作_広告デザイン_W1_制作進行_A_20260507 / キャンペーンID30 / 送信成功87件 / 失敗154件 / スキップ57件 / 補正クリック4社",
        "AI-SABI_Web制作_広告デザイン_W1_品質安定_B_20260507 / キャンペーンID31 / 送信成功54件 / 失敗77件 / スキップ31件 / 補正クリック4社",
        "AI-SABI_Web制作_広告デザイン_W2_制作進行_A_20260507 / キャンペーンID32 / 送信成功86件 / 失敗137件 / スキップ38件 / 補正クリック5社",
        "AI-SABI_Web制作_広告デザイン_W2_品質安定_B_20260507 / キャンペーンID33 / 送信成功55件 / 失敗81件 / スキップ24件 / 補正クリック2社",
        "AI-SABI_Web制作_広告デザイン_W3_制作進行_A_20260507 / キャンペーンID34 / 送信成功104件 / 失敗142件 / スキップ32件 / 補正クリック4社",
        "AI-SABI_Web制作_広告デザイン_W3_品質安定_B_20260507 / キャンペーンID35 / 送信成功46件 / 失敗82件 / スキップ14件 / 補正クリック2社",
        "AI-SABI_Web制作_広告デザイン_フォーム未達メール補完_20260507 / キャンペーンID36 / 下書き / 対象70件 / 予約未設定",
        "AI-SABI_Web制作_広告デザイン_休日検証_制作進行_A_20260502 / キャンペーンID37 / 予約済み / 2026-05-02 11:00 JST / send_count232件",
        "AI-SABI_Web制作_広告デザイン_休日検証_品質安定_B_20260502 / キャンペーンID38 / 予約済み / 2026-05-02 11:15 JST / send_count211件",
        "AI-SABI_Web制作_広告デザイン_短縮CTA_C_20260507 / キャンペーンID39 / 予約済み / 2026-05-07 11:00 JST / send_count420件",
        "AI-SABI_Web制作_広告デザイン_LINE相談導線_D_20260507 / キャンペーンID40 / 予約済み / 2026-05-07 11:15 JST / send_count343件",
        "AI-SABI_Web制作_広告デザイン_短縮CTA_C_20260508 / キャンペーンID41 / 予約済み / 2026-05-08 11:00 JST / send_count364件",
        "AI-SABI_Web制作_広告デザイン_LINE相談導線_D_20260508 / キャンペーンID42 / 予約済み / 2026-05-08 11:15 JST / send_count346件",
        "AI-SABI_Web制作_広告デザイン_フォーム未達メール補完_5月1日分_1_20260508 / キャンペーンID43 / 下書き / 対象92件 / 予約未設定",
        "AI-SABI_Web制作_広告デザイン_フォーム未達メール補完_5月1日分_2_20260511 / キャンペーンID44 / 下書き / 対象74件 / 予約未設定",
        "AI-SABI_Web制作_広告デザイン_休日継続_制作進行_A_20260503 / キャンペーンID45 / 予約済み / 2026-05-03 11:00 JST / send_count500件",
        "AI-SABI_Web制作_広告デザイン_休日継続_品質安定_B_20260503 / キャンペーンID46 / 予約済み / 2026-05-03 11:15 JST / send_count200件",
        "AI-SABI_Web制作_広告デザイン_休日継続_制作進行_A_20260504 / キャンペーンID47 / 予約済み / 2026-05-04 11:00 JST / send_count450件",
        "AI-SABI_Web制作_広告デザイン_休日継続_品質安定_B_20260504 / キャンペーンID48 / 予約済み / 2026-05-04 11:15 JST / send_count150件",
      ],
      lpStats: "5/1時点で広告・デザインLPはPV28、LINEクリック4、平均滞在227秒、平均スクロール90%。クリック補正は /api/tracking/clicks のキャンペーン名集計を正とし、公開画面には企業名・IDを載せない。",
    },
  },
  fastPdcaPlan: {
    title: "5/2休日初速・A厚め継続予約済み",
    goal:
      "5/2昼時点で休日でもクリックが出ているため、2日先までA厚め/B少量を予約し、検証できたタイミングで予約済み内容も更新する。",
    targetCandidates: 6642,
    expectedSuccess: "5/3-5/4予約send_count1,300件 / 5/7-5/8予約send_count1,473件",
    expectedClicks: "5/2昼時点の休日成功ベース5.6%が続けば5/3-5/4で約20社前後が目安",
    abAllocation: "5/2昼時点ではAが強い。5/3-5/4はAを約7割、Bを約3割に寄せ、5/7-5/8は既存予約のC/D新比較軸を維持する。",
    primaryFormSettings:
      "フォーム送信状態=未送信（または重複除外前提で全て） / メール送信状態=全て / メール保有=全て",
    emailFallbackSettings:
      "フォーム送信状態=失敗 + スキップ全部 / メール保有=メールあり / メール送信状態=未送信 / 1日100件上限",
    waves: [
      {
        step: "Wave 1",
        timing: "2026-05-01 13:05 / 13:15 配信済み",
        channel: "フォーム",
        volume: "実行460件 / 成功141件 / クリック8社",
        settings: "A: 87成功・4クリック、B: 54成功・4クリック。グループID32/33、キャンペーンID30/31。",
        purpose: "Bの初速が良く、A厚め判断をいったん保留",
      },
      {
        step: "Wave 2",
        timing: "2026-05-01 13:25 / 13:35 配信済み",
        channel: "フォーム",
        volume: "実行421件 / 成功141件 / クリック7社",
        settings: "A: 86成功・5クリック、B: 55成功・2クリック。グループID34/35、キャンペーンID32/33。",
        purpose: "Wave単位ではAが優位だが差は小さい",
      },
      {
        step: "Wave 3",
        timing: "2026-05-01 13:45 / 13:55 配信済み",
        channel: "フォーム",
        volume: "実行420件 / 成功150件 / クリック6社",
        settings: "A: 104成功・4クリック、B: 46成功・2クリック。グループID36/37、キャンペーンID34/35。",
        purpose: "クリック率は維持、LP側LINEクリックも確認",
      },
      {
        step: "Fallback",
        timing: "連休明け 2026-05-07以降",
        channel: "メール",
        volume: "既存70件 + 5/1分166件。1日100件以内で分割",
        settings: "既存ID36は4/30未達70件だけ。5/1未達166件は別グループ・別キャンペーンで作る。",
        purpose: "フォームで届かなかった企業だけを補完し、重複接触を避ける",
      },
      {
        step: "Next Scheduled 1",
        timing: "2026-05-02 11:00 / 11:15配信済み・集計中",
        channel: "フォーム",
        volume: "send_count443件 / 送信成功126件 / 補正クリック7社",
        settings: "休日A/B。Aは57成功・5クリック、Bは69成功・2クリック。グループID39/40、キャンペーンID37/38。",
        purpose: "休日でも反応が出るかを確認。昼時点ではAの初速が強い",
      },
      {
        step: "Next Scheduled 2",
        timing: "2026-05-03 11:00 / 11:15予約済み",
        channel: "フォーム",
        volume: "総対象1,166件 / send_count700件",
        settings: "A厚め500件、B少量200件。グループID47/48、キャンペーンID45/46。",
        purpose: "5/2昼時点でAが強いため、休日継続検証をA寄せで回す",
      },
      {
        step: "Next Scheduled 3",
        timing: "2026-05-04 11:00 / 11:15予約済み",
        channel: "フォーム",
        volume: "総対象937件 / send_count600件",
        settings: "A厚め450件、B少量150件。グループID49/50、キャンペーンID47/48。",
        purpose: "毎日確認できない前提で2日先まで予約し、5/3結果確認時に必要なら変更する",
      },
      {
        step: "Next Scheduled 4",
        timing: "2026-05-07 11:00 / 11:15予約済み",
        channel: "フォーム",
        volume: "総対象1,807件 / 想定処理763件 / 想定成功253件",
        settings: "C短縮CTA、D LINE相談導線。グループID41/42、キャンペーンID39/40。send_count420/343でツール側予約済み。",
        purpose: "大都市圏を含め、本文差分でクリック率とLINE到達の差を見る",
      },
      {
        step: "Next Scheduled 5",
        timing: "2026-05-08 11:00 / 11:15予約済み",
        channel: "フォーム",
        volume: "総対象1,682件 / 想定処理710件 / 想定成功236件",
        settings: "C/D追加。グループID43/44、キャンペーンID41/42。send_count364/346でツール側予約済み。",
        purpose: "1日だけの地域差を抑え、C/Dの再現性を見る",
      },
      {
        step: "Mail Draft",
        timing: "2026-05-08 14:00 / 2026-05-11 11:00候補",
        channel: "メール",
        volume: "5/1未達166件を92件・74件で分割",
        settings: "グループID45/46、キャンペーンID43/44。1日100件上限内、フォーム結果確認後に予約判断するため未予約。",
        purpose: "フォーム未達だけを補完し、メールなし・フォーム成功済み企業を除外する",
      },
    ],
    gates: [
      "キャンペーンID30-35はユーザーの明示承認によりツール側予約・配信完了。今後も予約/送信確定はユーザー確認後だけ行う。",
      "フォーム配信とメール補完は同じタイミングで予約しない。",
      "5/1未達メール補完はID36へ混ぜず、ジョブログ反映後に別グループ・別キャンペーンで作る。",
      "メール配信は最初は1日100件/アカウントを上限にし、100件を超える場合は日別またはアカウント別に分割する。",
      "ユーザー承認によりキャンペーンID37-42はツール側予約済み。キャンペーンID43-44のメール補完はフォーム結果確認後に判断するため未予約。",
      "2026-05-02昼時点の休日初速を受け、ユーザー承認によりキャンペーンID45-48を5/3-5/4分としてツール側予約済み。今後は毎回2-3日先まで仮予約し、結果確認できたタイミングで必要に応じて予約内容を更新する。",
      "テンプレート本文では {{tracking_url}} を使い、実URLを直書きしない。",
      "公開管理画面にはクリック企業名・企業IDを載せない。",
    ],
  },
  nav: [
    { id: "dashboard", label: "ダッシュボード", icon: "dashboard" },
    { id: "ab-test", label: "ABテスト設計", icon: "ab" },
    { id: "approval", label: "配信管理", icon: "approval" },
    { id: "results", label: "結果分析", icon: "results" },
    { id: "templates", label: "テンプレート", icon: "template" },
    { id: "segments", label: "セグメント", icon: "segment" },
  ],
  approvalMetrics: [
    { label: "本日配信完了", value: "2", unit: "件", icon: "approval" },
    { label: "本日送信成功", value: "126", unit: "件", icon: "calendar" },
    { label: "予約済みフォーム", value: "8", unit: "件", icon: "template" },
    { label: "次回フォーム総対象", value: "5,592", unit: "件", icon: "campaign" },
    { label: "メール補完", value: "236", unit: "件", icon: "results" },
  ],
  dashboard: {
    metrics: [
      { label: "本日送信成功", value: "126", unit: "件", trend: "5/2昼時点 / ID37-38", icon: "campaign" },
      { label: "本日クリック企業", value: "7", unit: "社", trend: "成功ベース5.6%", icon: "approval" },
      { label: "LINEクリック", value: "5", unit: "件", trend: "広告・デザインLP累計表示", icon: "results" },
      { label: "次回フォーム総対象", value: "5,592", unit: "件", trend: "5/3-5/4 + 5/7-5/8予約", icon: "target" },
      { label: "メール補完候補", value: "236", unit: "件", trend: "70 + 92 + 74で分割", icon: "line" },
    ],
    pipeline: [
      { industry: "前回: 静岡・長野", icon: "template", planning: 0, group: 2, template: 2, campaign: 2, waiting: 0, analyzing: 2 },
      { industry: "今回: 地方6県スケール", icon: "segment", planning: 0, group: 6, template: 2, campaign: 6, waiting: 0, analyzing: 6 },
      { industry: "5/1: 爆速PDCA", icon: "database", planning: 0, group: 7, template: 3, campaign: 7, waiting: 0, analyzing: 7 },
      { industry: "次回: 休日/平日/メール補完", icon: "approval", planning: 0, group: 8, template: 4, campaign: 8, waiting: 2, analyzing: 6 },
    ],
    tasks: [
      {
        title: "5/1配信結果を補正集計する",
        detail:
          "キャンペーンID30-35は配信完了。キャンペーン詳細クリックは0件のままなので、トラッキング一覧のキャンペーン名で補正集計する。",
        priority: "高",
        due: "完了",
      },
      {
        title: "フォーム送信状態の選び方に注意する",
        detail:
          "フォーム主配信は「未送信」。メール送信状態とメール保有はフォーム配信では絞らない。フォーム未達メール補完では、フォーム失敗+スキップ全部、メールあり、メール未送信を使う。",
        priority: "高",
        due: "設定時",
      },
      {
        title: "フォーム未達だけをメール補完する",
        detail:
          "現在の未達メール候補は236件。既存70件と5/1分166件を分け、1日100件以内で連休明けに分割する。",
        priority: "高",
        due: "5/7以降",
      },
      {
        title: "5/2・5/7・5/8フォームを予約済み",
        detail:
          "5/1は総対象3,082に対して処理済み1,301、成功432だったため、次回フォームは総対象4,539件、想定処理1,916件を6本に分けてツール側予約済み。",
        priority: "高",
        due: "予約済み",
      },
      {
        title: "メール補完は1日100件までに抑える",
        detail:
          "最初はスパム判定やアカウント規制を避けるため、1アカウントあたり1日100件を上限にする。100件を超える場合は日別または送信アカウント別に分割する。",
        priority: "高",
        due: "メール予約時",
      },
      {
        title: "予約はツール側を使う",
        detail:
          "既存ツールのキャンペーン詳細に日時予約が実装されたため、ローカル予約ワーカーは停止済み。5/2・5/7・5/8のフォーム6本はツール側予約で時間帯を分けた。",
        priority: "高",
        due: "完了",
      },
      {
        title: "次の分岐条件を決めておく",
        detail:
          "5/1はA=277成功/13クリック、B=155成功/8クリック。累計ではA/Bほぼ同率のため、短縮版CTAなど次の比較軸を追加する。",
        priority: "中",
        due: "結果確認時",
      },
      {
        title: "公開画面に企業名・IDを出さない",
        detail:
          "クリック企業の特定は既存ツール内だけで行い、この画面には集計値だけを載せる。",
        priority: "中",
        due: "常時",
      },
    ],
    resultSummary: [
      { label: "本日送信成功", value: "432", unit: "件" },
      { label: "本日クリック企業", value: "21", unit: "社" },
      { label: "本日補正クリック率", value: "4.9", unit: "%" },
      { label: "累計送信成功", value: "594", unit: "件" },
      { label: "累計クリック企業", value: "32", unit: "社" },
      { label: "LP閲覧", value: "28", unit: "PV" },
      { label: "LINEクリック", value: "4", unit: "件" },
    ],
    risks: [
      {
        title: "送信成功率は約3分の1",
        detail:
          "5/1は総対象3,082件のうち、ジョブ処理済み1,301件、送信成功432件。総対象ベースでは14.0%まで落ちるため、次回は総対象4,539件まで大きめに確保する。",
        action: "母数確保",
      },
      {
        title: "クリック集計の反映差",
        detail:
          "トラッキングタブではクリック企業が確認できる一方、キャンペーン詳細は0件のまま。現時点ではトラッキング補正値を正として扱う。",
        action: "補正集計",
      },
      {
        title: "失敗＋スキップ指定は補完専用",
        detail:
          "失敗＋スキップ全部は送信済み除外ではなく、フォーム未達だけを対象にする条件。主配信では使わず、メール補完で使う。",
        action: "条件修正",
      },
    ],
  },
  abTests: [
    {
      id: "ab-web-scale-001",
      name: "Web制作_広告デザイン_爆速PDCA",
      industry: "広告・デザイン",
      hypothesis:
        "広告・デザイン会社には、AI一般論よりも制作進行と文章業務の負担を具体化した方が反応する。5/1は総対象3,082件から処理済み1,301件・成功432件だったため、次回は総対象4,539件まで広げ、休日A/Bと平日C/Dで判断できる母数を作る。",
      segment:
        "IT・サービスDB / 広告・デザイン / 5/2休日A/B、5/7-5/8平日C/D、5/8-5/11フォーム未達メール補完",
      appealA: "制作進行の時短",
      appealB: "提案・報告文の品質安定",
      success: "送信成功率 / トラッキング補正クリック率 / LP閲覧 / LINEクリック",
      status: "結果確認中",
      subjectA: "{{company_name}}様へ、Web制作の提案文・進行連絡を整えるご案内",
      subjectB: "{{company_name}}様へ、提案・更新報告の品質を揃えるAI活用のご案内",
      introA:
        "制作そのもの以外に発生する提案文、要件整理、進行連絡、更新報告を軽くする切り口で初回接点を作る。",
      introB:
        "担当者ごとに表現や確認品質が変わりやすい提案・報告業務を安定させる切り口で初回接点を作る。",
      cta: "広告・デザイン向けLPの活用例を {{tracking_url}} で確認",
      bodyA: [
        "{{company_name}} 御中",
        "",
        "突然のご連絡失礼いたします。",
        "AI-SABIの仲西です。",
        "",
        "本日は、{{prefecture}}の広告・デザイン／Web制作会社様向けに、Web制作まわりの提案文、要件整理、進行連絡、更新報告を整えるAI活用について、情報提供としてご連絡しました。",
        "",
        "制作現場では、制作そのものに加えて、初回提案の文章化、修正内容の整理、顧客への進行共有などが日々積み重なりやすいかと思います。",
        "AI-SABIでは、いきなり大きなツール導入を行うのではなく、よく使う文章や確認項目を貴社の進め方に合わせて型化し、担当者の負担を少しずつ減らす形で伴走します。",
        "",
        "Web制作会社様向けの活用例を下記にまとめています。",
        "{{tracking_url}}",
        "",
        "提案文や進行連絡の整理に少しでもお役立ていただけそうでしたら、ご覧ください。",
        "",
        "どうぞよろしくお願いいたします。",
        "",
        "AI-SABI",
        "AI導入支援",
        "代表 仲西 匠",
      ].join("\n"),
      bodyB: [
        "{{company_name}} 御中",
        "",
        "突然のご連絡失礼いたします。",
        "AI-SABIの仲西です。",
        "",
        "本日は、{{prefecture}}で広告・デザイン領域の事業をされている企業様向けに、提案文や更新報告の品質を揃えるAI活用について、情報提供としてご連絡しました。",
        "",
        "Web制作やデザイン案件では、提案内容、進行報告、修正内容の伝え方が担当者ごとに変わりやすく、確認や手戻りの工数が増えることがあるかと思います。",
        "AI-SABIでは、貴社の言い回しや確認観点を整理し、AIで初稿作成と品質確認を行いやすい形に整えることで、少人数の体制でも提案・報告品質を揃えやすくする伴走を行います。",
        "",
        "Web制作会社様向けの活用例はこちらです。",
        "{{tracking_url}}",
        "",
        "提案文や更新報告の作成・確認に少しでもお役立ていただけそうでしたら、ご覧ください。",
        "",
        "どうぞよろしくお願いいたします。",
        "",
        "AI-SABI",
        "AI導入支援",
        "代表 仲西 匠",
      ].join("\n"),
      intent:
        "5/1までの累計ではA/Bがほぼ同率になったため、業種やLPは維持しつつ、次は休日/平日の曜日差、本文の短さ・CTA位置、LINE相談導線を新しい比較軸にする。",
      reaction:
        "制作現場の文章業務に近いと感じ、広告・デザイン向けLPを確認し、必要な場合はLINE相談へ進む。",
      diff:
        "Aは累計20社/369件、Bは累計12社/225件で、成功ベース補正クリック率は5.4%対5.3%。A/Bの勝敗は確定せず、現行A/Bはコントロールとして残す。",
      improve:
        "5/1未達166件はID36へ混ぜず別グループ化済み。メール補完は100件/日以内で分割し、次回フォームは総対象4,539件を5/2・5/7・5/8にツール側予約済み。",
    },
    {
      id: "ab-web-previous-001",
      name: "Web制作_広告デザイン_地方初回",
      industry: "広告・デザイン",
      hypothesis:
        "IT・ソフトウェア広めではなく、Web制作LPとの一致度が高い広告・デザイン企業へ対象を寄せると反応が出やすい",
      segment: "静岡A 96件指定→35件成功 / 長野B 77件指定→23件成功",
      appealA: "A: 制作進行の時短",
      appealB: "B: 提案・報告文の品質安定",
      success: "トラッキング補正クリック5社",
      status: "結果確認中",
      subjectA: "{{company_name}}様へ、Web制作の提案文・進行連絡を整えるご案内",
      subjectB: "{{company_name}}様へ、提案・更新報告の品質を揃えるAI活用のご案内",
      introA: "制作進行の文章業務を前面に出す。",
      introB: "提案・報告品質の安定を前面に出す。",
      cta: "{{tracking_url}} から詳細を確認",
      intent:
        "既存Web制作テストのクリック0件から、対象と文面を広告・デザイン向けに寄せた。",
      reaction:
        "クリックは出たが母数不足のため、次回は同じ軸で拡張する。",
      diff:
        "地域差が残るため勝敗ではなく反応有無の確認として扱う。",
      improve:
        "次回は地方6県に増やし、成功200件前後を狙う。",
    },
    {
      id: "ab-next-lane-001",
      name: "次フェーズ_業種LP切替候補",
      industry: "保留",
      hypothesis:
        "地方6県でクリック率が伸びない場合は、同じ広告・デザイン向け文面をいじるより、別業種LPまたは別詳細業種へ切り替える方が速い可能性がある",
      segment: "地方6県の結果確認後に決定",
      appealA: "広告・デザイン継続",
      appealB: "別業種LPへ切替",
      success: "補正クリック率 / LP閲覧 / LINEクリック",
      status: "保留",
      subjectA: "-",
      subjectB: "-",
      introA: "現行の勝ち筋が見えた場合のみ大都市圏へ展開。",
      introB: "クリック率が低い場合は別業種LPへ切り替える。",
      cta: "{{tracking_url}}",
      intent: "爆速PDCAの次の分岐を先に用意しておく。",
      reaction: "結果に応じて次アクションを迷わず切り替える。",
      diff: "今回は使わない。",
      improve: "作成済み3,082候補の爆速PDCA後に判断する。",
    },
  ],
  approvals: [
    {
      id: "cp-scale-niigata-a",
      reservationId: "res-20260430-niigata-a",
      campaign: "AI-SABI_Web制作_広告デザイン_新潟県_制作進行_A_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_新潟県_A_20260427",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID15 / active / 送信成功26件 / 失敗32件 / スキップ12件 / 補正クリック1社",
      target: 152,
      recommended: 152,
      sendableEstimate: 70,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:00 JST 配信済み",
      priority: "高",
      intent: "A案の制作進行短縮訴求を新潟県で確認する。",
      conditions: "IT・サービスDB / 広告・デザイン / 新潟県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "実行候補70件、送信成功26件、失敗32件、スキップ12件。",
      caution: "トラッキング補正クリック1社。キャンペーン詳細クリック0件だけで判断しない。",
    },
    {
      id: "cp-scale-yamaguchi-b",
      reservationId: "res-20260430-yamaguchi-b",
      campaign: "AI-SABI_Web制作_広告デザイン_山口県_品質安定_B_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_山口県_B_20260427",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID16 / active / 送信成功16件 / 失敗30件 / スキップ10件 / 補正クリック1社",
      target: 123,
      recommended: 123,
      sendableEstimate: 56,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:05 JST 配信済み",
      priority: "高",
      intent: "B案の提案・報告品質安定訴求を山口県で確認する。",
      conditions: "IT・サービスDB / 広告・デザイン / 山口県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "実行候補56件、送信成功16件、失敗30件、スキップ10件。",
      caution: "トラッキング補正クリック1社。B案は反応ありだがA案より弱め。",
    },
    {
      id: "cp-scale-miyazaki-a",
      reservationId: "res-20260430-miyazaki-a",
      campaign: "AI-SABI_Web制作_広告デザイン_宮崎県_制作進行_A_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_宮崎県_A_20260427",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID17 / active / 送信成功16件 / 失敗27件 / スキップ12件 / 補正クリック0社",
      target: 104,
      recommended: 104,
      sendableEstimate: 55,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:10 JST 配信済み",
      priority: "高",
      intent: "A案を九州地方でも確認し、新潟だけの地域差を避ける。",
      conditions: "IT・サービスDB / 広告・デザイン / 宮崎県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "実行候補55件、送信成功16件、失敗27件、スキップ12件。",
      caution: "クリック0社。地域差の可能性があるためA案全体では継続。",
    },
    {
      id: "cp-scale-kumamoto-b",
      reservationId: "res-20260430-kumamoto-b",
      campaign: "AI-SABI_Web制作_広告デザイン_熊本県_品質安定_B_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_熊本県_B_20260427",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID18 / active / 送信成功17件 / 失敗27件 / スキップ5件 / 補正クリック0社",
      target: 95,
      recommended: 95,
      sendableEstimate: 49,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:15 JST 配信済み",
      priority: "高",
      intent: "B案を九州地方でも確認し、山口だけの地域差を避ける。",
      conditions: "IT・サービスDB / 広告・デザイン / 熊本県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "実行候補49件、送信成功17件、失敗27件、スキップ5件。",
      caution: "クリック0社。B案は次回も少量継続し、A案との比較を残す。",
    },
    {
      id: "cp-scale-yamagata-b",
      reservationId: "res-20260430-yamagata-b",
      campaign: "AI-SABI_Web制作_広告デザイン_山形県_品質安定_B_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_山形県_B_20260427",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID19 / active / 送信成功14件 / 失敗16件 / スキップ6件 / 補正クリック0社",
      target: 108,
      recommended: 108,
      sendableEstimate: 36,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:25 JST 配信済み",
      priority: "高",
      intent: "4県だけでは母数不足のため追加し、B側の指定母数を補う。",
      conditions: "IT・サービスDB / 広告・デザイン / 山形県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "実行候補36件、送信成功14件、失敗16件、スキップ6件。",
      caution: "クリック0社。B案の追加判断は次回大規模の少量枠で見る。",
    },
    {
      id: "cp-scale-fukui-a",
      reservationId: "res-20260430-fukui-a",
      campaign: "AI-SABI_Web制作_広告デザイン_福井県_制作進行_A_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_福井県_A_20260427",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID20 / active / 送信成功15件 / 失敗17件 / スキップ3件 / 補正クリック3社",
      target: 80,
      recommended: 80,
      sendableEstimate: 35,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-04-30 12:20 JST 配信済み",
      priority: "高",
      intent: "A/B指定母数をほぼ均等にしつつ、地方県の追加検証を行う。",
      conditions: "IT・サービスDB / 広告・デザイン / 福井県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "実行候補35件、送信成功15件、失敗17件、スキップ3件。",
      caution: "トラッキング補正クリック3社。今回最も反応が強く、A案継続の根拠にする。",
    },
    {
      id: "cp-fast-w1-a",
      reservationId: "tool-draft-20260507-w1-a",
      campaign: "AI-SABI_Web制作_広告デザイン_W1_制作進行_A_20260507",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_W1_A_未送信_20260507",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID30 / completed / 送信成功87件 / 失敗154件 / スキップ57件 / 補正クリック4社",
      target: 652,
      recommended: 298,
      sendableEstimate: 298,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-01 13:05 JST 配信済み",
      priority: "高",
      intent: "A案を北海道・茨城県・徳島県で拡張し、初速と送信成功率を確認する。",
      conditions: "IT・サービスDB / 広告・デザイン / 北海道・茨城県・徳島県 / フォーム送信状態=未送信",
      exclusions: "実行298件、送信成功87件、失敗154件、スキップ57件。",
      caution: "トラッキング補正クリック4社。キャンペーン詳細クリック0件のため補正値で見る。",
    },
    {
      id: "cp-fast-w1-b",
      reservationId: "tool-draft-20260507-w1-b",
      campaign: "AI-SABI_Web制作_広告デザイン_W1_品質安定_B_20260507",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_W1_B_未送信_20260507",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID31 / completed / 送信成功54件 / 失敗77件 / スキップ31件 / 補正クリック4社",
      target: 389,
      recommended: 162,
      sendableEstimate: 162,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-01 13:15 JST 配信済み",
      priority: "高",
      intent: "B案を愛知県で残し、A偏重にしすぎず比較軸を維持する。",
      conditions: "IT・サービスDB / 広告・デザイン / 愛知県 / フォーム送信状態=未送信",
      exclusions: "実行162件、送信成功54件、失敗77件、スキップ31件。",
      caution: "トラッキング補正クリック4社。成功ベースではこの波のBが高め。",
    },
    {
      id: "cp-fast-w2-a",
      reservationId: "tool-draft-20260507-w2-a",
      campaign: "AI-SABI_Web制作_広告デザイン_W2_制作進行_A_20260507",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_W2_A_未送信_20260507",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID32 / completed / 送信成功86件 / 失敗137件 / スキップ38件 / 補正クリック5社",
      target: 660,
      recommended: 261,
      sendableEstimate: 261,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-01 13:25 JST 配信済み",
      priority: "高",
      intent: "A案を埼玉県・三重県・秋田県で広げ、昼帯反応を見る。",
      conditions: "IT・サービスDB / 広告・デザイン / 埼玉県・三重県・秋田県 / フォーム送信状態=未送信",
      exclusions: "実行261件、送信成功86件、失敗137件、スキップ38件。",
      caution: "トラッキング補正クリック5社。5/1の単体キャンペーンでは最多クリック。",
    },
    {
      id: "cp-fast-w2-b",
      reservationId: "tool-draft-20260507-w2-b",
      campaign: "AI-SABI_Web制作_広告デザイン_W2_品質安定_B_20260507",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_W2_B_未送信_20260507",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID33 / completed / 送信成功55件 / 失敗81件 / スキップ24件 / 補正クリック2社",
      target: 368,
      recommended: 160,
      sendableEstimate: 160,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-01 13:35 JST 配信済み",
      priority: "高",
      intent: "B案を兵庫県・鳥取県で確認し、都道府県差をならす。",
      conditions: "IT・サービスDB / 広告・デザイン / 兵庫県・鳥取県 / フォーム送信状態=未送信",
      exclusions: "実行160件、送信成功55件、失敗81件、スキップ24件。",
      caution: "トラッキング補正クリック2社。Bは全体ではAとほぼ同率。",
    },
    {
      id: "cp-fast-w3-a",
      reservationId: "tool-draft-20260507-w3-a",
      campaign: "AI-SABI_Web制作_広告デザイン_W3_制作進行_A_20260507",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_W3_A_未送信_20260507",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID34 / completed / 送信成功104件 / 失敗142件 / スキップ32件 / 補正クリック4社",
      target: 660,
      recommended: 278,
      sendableEstimate: 278,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-01 13:45 JST 配信済み",
      priority: "高",
      intent: "A案を千葉県・福岡県・群馬県で確認し、15時台の反応を見る。",
      conditions: "IT・サービスDB / 広告・デザイン / 千葉県・福岡県・群馬県 / フォーム送信状態=未送信",
      exclusions: "実行278件、送信成功104件、失敗142件、スキップ32件。",
      caution: "トラッキング補正クリック4社。成功数は5/1最多。",
    },
    {
      id: "cp-fast-w3-b",
      reservationId: "tool-draft-20260507-w3-b",
      campaign: "AI-SABI_Web制作_広告デザイン_W3_品質安定_B_20260507",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_W3_B_未送信_20260507",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID35 / completed / 送信成功46件 / 失敗82件 / スキップ14件 / 補正クリック2社",
      target: 353,
      recommended: 142,
      sendableEstimate: 142,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "配信済み",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-01 13:55 JST 配信済み",
      priority: "高",
      intent: "B案を沖縄県・京都府で少量継続する。",
      conditions: "IT・サービスDB / 広告・デザイン / 沖縄県・京都府 / フォーム送信状態=未送信",
      exclusions: "実行142件、送信成功46件、失敗82件、スキップ14件。",
      caution: "トラッキング補正クリック2社。Bは継続候補だが勝敗確定ではない。",
    },
    {
      id: "cp-fast-email-fallback",
      reservationId: "tool-draft-20260507-email-fallback",
      campaign: "AI-SABI_Web制作_広告デザイン_フォーム未達メール補完_20260507",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_フォーム未達メール補完_20260507",
      template: "AI-SABI_Web制作_フォーム未達メール補完_20260507",
      existingCampaign: "キャンペーンID36 / draft / scheduled_at未設定 / メールテンプレートID12",
      target: 236,
      recommended: 100,
      sendableEstimate: 236,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "下書き作成済み",
      userStatus: "フォーム後",
      status: "補完候補",
      deliveryChannel: "メール配信",
      scheduledAt: "フォーム配信結果反映後に判断",
      priority: "中",
      intent: "フォームで届かなかった企業のうち、メールあり・メール未送信だけを補完する。4/30分70件と5/1分166件は分けて扱う。",
      conditions: "フォーム送信状態=失敗+スキップ全部 / メール保有=メールあり / メール送信状態=未送信",
      exclusions: "フォーム成功済み企業とメールなし企業を除外。現在のメール補完候補は合計236件。",
      caution: "フォーム配信と同時刻に予約しない。1日100件上限のため、既存70件、5/1分92件、5/1分74件のように分割する。",
    },
    {
      id: "cp-next-holiday-a",
      reservationId: "tool-scheduled-20260502-holiday-a",
      campaign: "AI-SABI_Web制作_広告デザイン_休日検証_制作進行_A_20260502",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_休日検証_A_未送信_20260502",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID37 / scheduled / 2026-05-02 11:00 JST / グループID39 / ジョブpending",
      target: 549,
      recommended: 232,
      sendableEstimate: 77,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "ツール側予約済み",
      userStatus: "予約済み",
      status: "予約中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-02 11:00 JST予約済み",
      priority: "高",
      intent: "休日は伸びにくい前提を検証するため、既存A訴求を休日枠で少量確認する。",
      conditions: "IT・サービスDB / 広告・デザイン / 栃木県・岐阜県・石川県・高知県・佐賀県 / フォーム送信状態=未送信",
      exclusions: "メール送信状態・メール保有はフォーム配信では絞らない。想定処理232件、想定成功77件。",
      caution: "休日検証は曜日差の参考値。平日C/Dと同じ勝敗軸で混ぜない。",
    },
    {
      id: "cp-next-holiday-b",
      reservationId: "tool-scheduled-20260502-holiday-b",
      campaign: "AI-SABI_Web制作_広告デザイン_休日検証_品質安定_B_20260502",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_休日検証_B_未送信_20260502",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID38 / scheduled / 2026-05-02 11:15 JST / グループID40 / ジョブpending",
      target: 501,
      recommended: 211,
      sendableEstimate: 70,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "ツール側予約済み",
      userStatus: "予約済み",
      status: "予約中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-02 11:15 JST予約済み",
      priority: "高",
      intent: "休日検証でもBを残し、Aだけの曜日差にしない。",
      conditions: "IT・サービスDB / 広告・デザイン / 宮城県・福島県・富山県・山梨県・香川県 / フォーム送信状態=未送信",
      exclusions: "メール送信状態・メール保有はフォーム配信では絞らない。想定処理211件、想定成功70件。",
      caution: "休日結果は反応が弱くても即停止材料にせず、平日結果と分けて見る。",
    },
    {
      id: "cp-next-holiday-followup-a-0503",
      reservationId: "tool-scheduled-20260503-holiday-a",
      campaign: "AI-SABI_Web制作_広告デザイン_休日継続_制作進行_A_20260503",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_休日継続_A_未送信_20260503",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID45 / scheduled / 2026-05-03 11:00 JST / グループID47 / ジョブpending",
      target: 690,
      recommended: 500,
      sendableEstimate: 140,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "ツール側予約済み",
      userStatus: "予約済み",
      status: "予約中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-03 11:00 JST予約済み",
      priority: "高",
      intent: "5/2昼時点でAのクリック率が強いため、休日継続検証をA厚めで回す。",
      conditions: "IT・サービスDB / 広告・デザイン / 栃木県・岐阜県・石川県・高知県・佐賀県・岡山県・広島県・愛媛県 / フォーム送信状態=未送信",
      exclusions: "既送信企業は未送信フィルターで除外。メール送信状態・メール保有はフォーム配信では絞らない。",
      caution: "夜時点の5/2再集計でA優位が崩れた場合は、以後の予約比率を見直す。",
    },
    {
      id: "cp-next-holiday-followup-b-0503",
      reservationId: "tool-scheduled-20260503-holiday-b",
      campaign: "AI-SABI_Web制作_広告デザイン_休日継続_品質安定_B_20260503",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_休日継続_B_未送信_20260503",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID46 / scheduled / 2026-05-03 11:15 JST / グループID48 / ジョブpending",
      target: 476,
      recommended: 200,
      sendableEstimate: 56,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "ツール側予約済み",
      userStatus: "予約済み",
      status: "予約中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-03 11:15 JST予約済み",
      priority: "中",
      intent: "Bは5/2昼時点で弱めだが、完全停止せず休日比較用に少量残す。",
      conditions: "IT・サービスDB / 広告・デザイン / 宮城県・福島県・富山県・山梨県・香川県・島根県・長崎県 / フォーム送信状態=未送信",
      exclusions: "既送信企業は未送信フィルターで除外。メール送信状態・メール保有はフォーム配信では絞らない。",
      caution: "Bのクリックが伸びない場合は、5/4以降のB比率をさらに下げる。",
    },
    {
      id: "cp-next-holiday-followup-a-0504",
      reservationId: "tool-scheduled-20260504-holiday-a",
      campaign: "AI-SABI_Web制作_広告デザイン_休日継続_制作進行_A_20260504",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_休日継続_A_未送信_20260504",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID47 / scheduled / 2026-05-04 11:00 JST / グループID49 / ジョブpending",
      target: 729,
      recommended: 450,
      sendableEstimate: 126,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "ツール側予約済み",
      userStatus: "予約済み",
      status: "予約中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-04 11:00 JST予約済み",
      priority: "高",
      intent: "毎日確認できない前提で、A厚めの休日継続枠を2日先まで確保する。",
      conditions: "IT・サービスDB / 広告・デザイン / 新潟県・宮崎県・福井県・茨城県・徳島県・三重県・秋田県・群馬県・滋賀県 / フォーム送信状態=未送信",
      exclusions: "既送信企業は未送信フィルターで除外。メール送信状態・メール保有はフォーム配信では絞らない。",
      caution: "5/3結果確認ができた場合は、必要に応じてこの予約内容を変更する。",
    },
    {
      id: "cp-next-holiday-followup-b-0504",
      reservationId: "tool-scheduled-20260504-holiday-b",
      campaign: "AI-SABI_Web制作_広告デザイン_休日継続_品質安定_B_20260504",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_休日継続_B_未送信_20260504",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID48 / scheduled / 2026-05-04 11:15 JST / グループID50 / ジョブpending",
      target: 208,
      recommended: 150,
      sendableEstimate: 42,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "ツール側予約済み",
      userStatus: "予約済み",
      status: "予約中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-04 11:15 JST予約済み",
      priority: "中",
      intent: "B比較枠を最低限残し、Aだけで曜日差を判断しない。",
      conditions: "IT・サービスDB / 広告・デザイン / 山口県・熊本県・山形県・鳥取県 / フォーム送信状態=未送信",
      exclusions: "既送信企業は未送信フィルターで除外。メール送信状態・メール保有はフォーム配信では絞らない。",
      caution: "Bを広げる判断は、5/2夜または5/3の実数を見てからにする。",
    },
    {
      id: "cp-next-weekday-c-0507",
      reservationId: "tool-scheduled-20260507-c",
      campaign: "AI-SABI_Web制作_広告デザイン_短縮CTA_C_20260507",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_短縮CTA_C_未送信_20260507",
      template: "AI-SABI_Web制作_短縮CTA_C_20260507",
      existingCampaign: "キャンペーンID39 / scheduled / 2026-05-07 11:00 JST / グループID41 / テンプレートID13 / ジョブpending",
      target: 994,
      recommended: 420,
      sendableEstimate: 139,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "ツール側予約済み",
      userStatus: "予約済み",
      status: "予約中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-07 11:00 JST予約済み",
      priority: "高",
      intent: "短縮CTAで本文を軽くし、クリック率が上がるかを見る。",
      conditions: "IT・サービスDB / 広告・デザイン / 東京都・神奈川県 / フォーム送信状態=未送信",
      exclusions: "メール送信状態・メール保有はフォーム配信では絞らない。想定処理420件、想定成功139件。",
      caution: "大都市圏を含むため、予約確定前に件数と時刻を再確認する。",
    },
    {
      id: "cp-next-weekday-d-0507",
      reservationId: "tool-scheduled-20260507-d",
      campaign: "AI-SABI_Web制作_広告デザイン_LINE相談導線_D_20260507",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_LINE相談導線_D_未送信_20260507",
      template: "AI-SABI_Web制作_LINE相談導線_D_20260507",
      existingCampaign: "キャンペーンID40 / scheduled / 2026-05-07 11:15 JST / グループID42 / テンプレートID14 / ジョブpending",
      target: 813,
      recommended: 343,
      sendableEstimate: 114,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "ツール側予約済み",
      userStatus: "予約済み",
      status: "予約中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-07 11:15 JST予約済み",
      priority: "高",
      intent: "LP確認後にLINE相談へ進む導線を本文上で自然に明確化する。",
      conditions: "IT・サービスDB / 広告・デザイン / 大阪府・兵庫県・奈良県・和歌山県・京都府 / フォーム送信状態=未送信",
      exclusions: "メール送信状態・メール保有はフォーム配信では絞らない。想定処理343件、想定成功114件。",
      caution: "C案との比較ではLINEクリックも合わせて見る。",
    },
    {
      id: "cp-next-weekday-c-0508",
      reservationId: "tool-scheduled-20260508-c",
      campaign: "AI-SABI_Web制作_広告デザイン_短縮CTA_C_20260508",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_短縮CTA_C_未送信_20260508",
      template: "AI-SABI_Web制作_短縮CTA_C_20260507",
      existingCampaign: "キャンペーンID41 / scheduled / 2026-05-08 11:00 JST / グループID43 / テンプレートID13 / ジョブpending",
      target: 863,
      recommended: 364,
      sendableEstimate: 121,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "ツール側予約済み",
      userStatus: "予約済み",
      status: "予約中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-08 11:00 JST予約済み",
      priority: "高",
      intent: "C案の再現性を別都道府県群で確認する。",
      conditions: "IT・サービスDB / 広告・デザイン / 北海道・愛知県・静岡県・長野県・青森県・岩手県 / フォーム送信状態=未送信",
      exclusions: "メール送信状態・メール保有はフォーム配信では絞らない。想定処理364件、想定成功121件。",
      caution: "5/7分だけで判断せず、2日分でC案の傾向を見る。",
    },
    {
      id: "cp-next-weekday-d-0508",
      reservationId: "tool-scheduled-20260508-d",
      campaign: "AI-SABI_Web制作_広告デザイン_LINE相談導線_D_20260508",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_LINE相談導線_D_未送信_20260508",
      template: "AI-SABI_Web制作_LINE相談導線_D_20260507",
      existingCampaign: "キャンペーンID42 / scheduled / 2026-05-08 11:15 JST / グループID44 / テンプレートID14 / ジョブpending",
      target: 819,
      recommended: 346,
      sendableEstimate: 115,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "ツール側予約済み",
      userStatus: "予約済み",
      status: "予約中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "2026-05-08 11:15 JST予約済み",
      priority: "高",
      intent: "D案の再現性とLINE相談導線の効き方を別都道府県群で確認する。",
      conditions: "IT・サービスDB / 広告・デザイン / 埼玉県・千葉県・福岡県・沖縄県・鹿児島県・大分県 / フォーム送信状態=未送信",
      exclusions: "メール送信状態・メール保有はフォーム配信では絞らない。想定処理346件、想定成功115件。",
      caution: "D案はクリックだけでなくLINEクリックも評価する。",
    },
    {
      id: "cp-next-email-0508",
      reservationId: "tool-draft-20260508-email",
      campaign: "AI-SABI_Web制作_広告デザイン_フォーム未達メール補完_5月1日分_1_20260508",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_フォーム未達メール補完_5月1日分_1_20260508",
      template: "AI-SABI_Web制作_フォーム未達メール補完_20260507",
      existingCampaign: "キャンペーンID43 / draft / scheduled_at未設定 / グループID45 / メールテンプレートID12",
      target: 92,
      recommended: 92,
      sendableEstimate: 92,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "下書き作成済み",
      userStatus: "未予約",
      status: "補完候補",
      deliveryChannel: "メール配信",
      scheduledAt: "2026-05-08 14:00 JST候補 / 未予約",
      priority: "中",
      intent: "5/1フォーム未達のうち、メールあり・メール未送信だけを100件上限内で補完する。",
      conditions: "フォーム送信状態=失敗+スキップ全部 / メール保有=メールあり / メール送信状態=未送信",
      exclusions: "フォーム成功済み企業、メールなし企業、メール送信済み企業を除外。",
      caution: "フォーム新規配信と時間をずらし、1日100件上限を守る。",
    },
    {
      id: "cp-next-email-0511",
      reservationId: "tool-draft-20260511-email",
      campaign: "AI-SABI_Web制作_広告デザイン_フォーム未達メール補完_5月1日分_2_20260511",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_フォーム未達メール補完_5月1日分_2_20260511",
      template: "AI-SABI_Web制作_フォーム未達メール補完_20260507",
      existingCampaign: "キャンペーンID44 / draft / scheduled_at未設定 / グループID46 / メールテンプレートID12",
      target: 74,
      recommended: 74,
      sendableEstimate: 74,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "下書き作成済み",
      userStatus: "未予約",
      status: "補完候補",
      deliveryChannel: "メール配信",
      scheduledAt: "2026-05-11 11:00 JST候補 / 未予約",
      priority: "中",
      intent: "5/1フォーム未達メール補完の2分割目として、100件上限内で安全に補完する。",
      conditions: "フォーム送信状態=失敗+スキップ全部 / メール保有=メールあり / メール送信状態=未送信",
      exclusions: "フォーム成功済み企業、メールなし企業、メール送信済み企業を除外。",
      caution: "5/8メール補完の結果を確認してから予約確定するのが安全。",
    },
    {
      id: "cp-web-a",
      campaign: "AI-SABI_Web制作_広告デザイン_静岡県_制作進行_A_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_静岡県_A_20260427",
      template: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      existingCampaign: "キャンペーンID13 / 送信済み / 送信成功35件 / トラッキング補正3社",
      target: 226,
      recommended: 96,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "結果確認中",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "配信済み",
      priority: "中",
      intent: "前回A案の結果保持。",
      conditions: "IT・サービスDB / 広告・デザイン / 静岡県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "送信成功35件、失敗50件、スキップ11件。",
      caution: "キャンペーン詳細側クリック0件のため、トラッキング補正で見る。",
    },
    {
      id: "cp-web-b",
      campaign: "AI-SABI_Web制作_広告デザイン_長野県_品質安定_B_20260427",
      industry: "広告・デザイン",
      group: "AI-SABI_広告デザイン_ITサービス_長野県_B_20260427",
      template: "AI-SABI_Web制作_提案報告品質_B_20260427",
      existingCampaign: "キャンペーンID14 / 送信済み / 送信成功23件 / トラッキング補正2社",
      target: 178,
      recommended: 77,
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      check: "結果確認中",
      userStatus: "送信済み",
      status: "分析中",
      deliveryChannel: "フォーム配信",
      scheduledAt: "配信済み",
      priority: "中",
      intent: "前回B案の結果保持。",
      conditions: "IT・サービスDB / 広告・デザイン / 長野県 / スクレイピング条件なし / コンタクト条件なし",
      exclusions: "送信成功23件、失敗44件、スキップ10件。",
      caution: "キャンペーン詳細側クリック0件のため、トラッキング補正で見る。",
    },
  ],
  results: {
    metrics: [
      { label: "本日送信成功", value: "432", unit: "件", icon: "approval" },
      { label: "本日補正クリック", value: "21", unit: "社", icon: "results" },
      { label: "本日クリック率", value: "4.9", unit: "%", icon: "results" },
      { label: "累計送信成功", value: "594", unit: "件", icon: "target" },
      { label: "累計補正クリック", value: "32", unit: "社", icon: "campaign" },
      { label: "メール補完候補", value: "236", unit: "件", icon: "lock" },
    ],
    comparisons: [
      {
        test: "5/1 A_制作進行",
        subject: "北海道ほか9県",
        intro: "制作進行の文章業務",
        cta: "{{tracking_url}}",
        click: "13社 / 277件 = 4.7%",
        line: "LP側LINEクリックあり",
        decision: "継続",
        next: "既存A/Bの勝敗は保留",
      },
      {
        test: "5/1 B_品質安定",
        subject: "愛知ほか4府県",
        intro: "品質安定と確認工数",
        cta: "{{tracking_url}}",
        click: "8社 / 155件 = 5.2%",
        line: "LP側LINEクリックあり",
        decision: "継続",
        next: "Bも落とさず、次は短縮版CTAを比較",
      },
      {
        test: "累計",
        subject: "4/27-5/1 広告・デザイン",
        intro: "同一LP・同一A/B",
        cta: "{{tracking_url}}",
        click: "32社 / 594件 = 5.4%",
        line: "広告・デザインLP LINEクリック4件",
        decision: "拡大可",
        next: "連休明けはメール補完と新比較軸を分ける",
      },
    ],
    failures: [
      { label: "送信成功率", value: 33 },
      { label: "失敗率", value: 52 },
      { label: "スキップ率", value: 15 },
      { label: "クリック率", value: 5 },
    ],
    improvements: [
      {
        title: "今回の判断",
        text:
          "広告・デザインLPとAI-SABI訴求は継続。5/1も成功432件から21社クリック、LP側LINEクリック4件が出ており、反応は確認できている。",
      },
      {
        title: "A/B判断",
        text:
          "5/1単体ではBがわずかに上、累計ではA=5.4%、B=5.3%でほぼ同率。A厚めを続ける根拠は弱まったため、次は既存A/Bを勝敗確定せず、短縮版CTAなど新しい差分を検証する。",
      },
      {
        title: "メール補完の進め方",
        text:
          "メール補完候補は合計236件。4/30分70件と5/1分166件を混ぜず、1日100件以内で連休明けに分割する。",
      },
      {
        title: "フォーム新規配信の進め方",
        text:
          "送信不可が多く総対象から実際の成功数が小さくなるため、次回フォームは総対象4,539件まで広げ、5/2休日A/B、5/7-5/8平日C/Dとしてツール側予約済み。",
      },
      {
        title: "集計で守ること",
        text:
          "キャンペーン詳細のクリック反映が遅れる場合は、トラッキングタブのクリック企業ID/企業名をジョブログへ照合する。公開管理画面には企業名やIDを出さない。",
      },
      {
        title: "停止すること",
        text:
          "ローカル予約ワーカーの再登録、フォーム配信とメール補完の同時予約、ID36への5/1未達分混在、キャンペーン詳細クリック0件だけで反応なしと判断することは避ける。",
      },
    ],
  },
  templates: [
    {
      name: "AI-SABI_Web制作_制作進行短縮_A_20260427",
      industry: "広告・デザイン",
      appeal: "制作進行の時短",
      subject: "{{company_name}}様へ、Web制作の提案文・進行連絡を整えるご案内",
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      count: 369,
      click: "20社 / 5.4%",
      updated: "2026/05/01 配信結果反映",
      label: "継続",
    },
    {
      name: "AI-SABI_Web制作_提案報告品質_B_20260427",
      industry: "広告・デザイン",
      appeal: "提案・報告文の品質安定",
      subject: "{{company_name}}様へ、提案・更新報告の品質を揃えるAI活用のご案内",
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      count: 225,
      click: "12社 / 5.3%",
      updated: "2026/05/01 配信結果反映",
      label: "継続",
    },
    {
      name: "AI-SABI_Web制作_フォーム未達メール補完_20260507",
      industry: "広告・デザイン",
      appeal: "フォーム未達のメール補完",
      subject: "{{company_name}}様へ、Web制作業務のAI活用について",
      lp: "広告・デザイン向けLP / {{tracking_url}} / 送信責任者表示あり",
      count: 0,
      click: "-",
      updated: "2026/05/01 補完候補236件へ更新",
      label: "下書き",
    },
    {
      name: "AI-SABI_Web制作_短縮CTA_C_20260507",
      industry: "広告・デザイン",
      appeal: "本文短縮・CTA前倒し",
      subject: "{{company_name}}様へ、Web制作まわりの文章業務を軽くするAI活用のご案内",
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      count: 0,
      click: "-",
      updated: "2026/05/01 テンプレートID13作成・フォーム予約済み",
      label: "予約中",
    },
    {
      name: "AI-SABI_Web制作_LINE相談導線_D_20260507",
      industry: "広告・デザイン",
      appeal: "LP確認後のLINE相談導線",
      subject: "{{company_name}}様へ、Web制作業務の文章作成・確認を整えるAI活用のご案内",
      lp: "広告・デザイン向けLP / {{tracking_url}}",
      count: 0,
      click: "-",
      updated: "2026/05/01 テンプレートID14作成・フォーム予約済み",
      label: "予約中",
    },
    {
      name: "WEB制作（テスト）",
      industry: "IT・ソフトウェア",
      appeal: "Web制作業務のAI活用",
      subject: "Web制作業務のAI活用・業務改善について",
      lp: "Web制作向けLP",
      count: 23,
      click: "0%",
      updated: "2026/04/20",
      label: "見直し",
    },
    {
      name: "システム開発_候補",
      industry: "IT・ソフトウェア",
      appeal: "開発進行の整理",
      subject: "開発案件の要件整理・進行共有をAIで整えるご案内",
      lp: "システム開発向けLP / {{tracking_url}}",
      count: 0,
      click: "-",
      updated: "保留",
      label: "保留",
    },
  ],
  segments: [
    {
      name: "広告デザイン_ITサービス_静岡県_A",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "静岡県",
      estimated: 226,
      sendable: 35,
      excluded: "失敗50 / スキップ11 / クリック補正3社",
      order: "A配信済み",
      group: "作成済み / ID 18",
    },
    {
      name: "広告デザイン_ITサービス_長野県_B",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "長野県",
      estimated: 178,
      sendable: 23,
      excluded: "失敗44 / スキップ10 / クリック補正2社",
      order: "B配信済み",
      group: "作成済み / ID 19",
    },
    {
      name: "広告デザイン_ITサービス_新潟県_A",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "新潟県",
      estimated: 152,
      sendable: 26,
      excluded: "失敗32 / スキップ12 / クリック補正1社",
      order: "A配信済み",
      group: "作成済み / ID 20",
    },
    {
      name: "広告デザイン_ITサービス_山口県_B",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "山口県",
      estimated: 123,
      sendable: 16,
      excluded: "失敗30 / スキップ10 / クリック補正1社",
      order: "B配信済み",
      group: "作成済み / ID 21",
    },
    {
      name: "広告デザイン_ITサービス_宮崎県_A",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "宮崎県",
      estimated: 104,
      sendable: 16,
      excluded: "失敗27 / スキップ12 / クリック補正0社",
      order: "A配信済み",
      group: "作成済み / ID 22",
    },
    {
      name: "広告デザイン_ITサービス_熊本県_B",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "熊本県",
      estimated: 95,
      sendable: 17,
      excluded: "失敗27 / スキップ5 / クリック補正0社",
      order: "B配信済み",
      group: "作成済み / ID 23",
    },
    {
      name: "広告デザイン_ITサービス_山形県_B",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "山形県",
      estimated: 108,
      sendable: 14,
      excluded: "失敗16 / スキップ6 / クリック補正0社",
      order: "B配信済み",
      group: "作成済み / ID 24",
    },
    {
      name: "広告デザイン_ITサービス_福井県_A",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "福井県",
      estimated: 80,
      sendable: 15,
      excluded: "失敗17 / スキップ3 / クリック補正3社",
      order: "A配信済み",
      group: "作成済み / ID 25",
    },
    {
      name: "広告デザイン_爆速PDCAフォーム候補",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "北海道・茨城・徳島・愛知・埼玉・三重・秋田・兵庫・鳥取・千葉・福岡・群馬・沖縄・京都",
      estimated: 3082,
      sendable: 432,
      excluded: "1,301件実行、送信成功432件、失敗673件、スキップ196件、補正クリック21社。",
      order: "配信済み",
      group: "作成済み / ID 32-37",
    },
    {
      name: "広告デザイン_フォーム未達メール補完_4月分",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "静岡・長野・新潟・山口・宮崎・熊本・山形・福井",
      estimated: 70,
      sendable: 70,
      excluded: "フォーム送信状態=失敗 + スキップ全部 / メール保有=メールあり / メール送信状態=未送信。メールなし企業は除外。",
      order: "フォーム後に別枠",
      group: "作成済み / ID 38",
    },
    {
      name: "広告デザイン_フォーム未達メール補完_5月1日分",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "北海道・茨城・徳島・愛知・埼玉・三重・秋田・兵庫・鳥取・千葉・福岡・群馬・沖縄・京都",
      estimated: 166,
      sendable: 166,
      excluded: "5/1配信の失敗・スキップのうち、メールあり・メール未送信。既存ID36へ混ぜず、92件と74件に分割済み。",
      order: "5/8・5/11候補",
      group: "作成済み / ID 45-46",
    },
    {
      name: "広告デザイン_休日検証_A/B_20260502",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "栃木・岐阜・石川・高知・佐賀 / 宮城・福島・富山・山梨・香川",
      estimated: 1050,
      sendable: 147,
      excluded: "総対象1,050件、想定処理443件、想定成功147件。フォーム送信状態=未送信。",
      order: "休日検証 / 予約済み",
      group: "作成済み / ID 39-40",
    },
    {
      name: "広告デザイン_平日C/D_20260507",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "東京・神奈川 / 大阪・兵庫・奈良・和歌山・京都",
      estimated: 1807,
      sendable: 253,
      excluded: "総対象1,807件、想定処理763件、想定成功253件。フォーム送信状態=未送信。",
      order: "C/D検証 / 予約済み",
      group: "作成済み / ID 41-42",
    },
    {
      name: "広告デザイン_平日C/D_20260508",
      db: "IT・サービス",
      industry: "広告・デザイン",
      pref: "北海道・愛知・静岡・長野・青森・岩手 / 埼玉・千葉・福岡・沖縄・鹿児島・大分",
      estimated: 1682,
      sendable: 236,
      excluded: "総対象1,682件、想定処理710件、想定成功236件。フォーム送信状態=未送信。",
      order: "C/D検証 / 予約済み",
      group: "作成済み / ID 43-44",
    },
    {
      name: "次フェーズ_別業種LP切替候補",
      db: "未定",
      industry: "未定",
      pref: "地方県優先",
      estimated: 0,
      sendable: 0,
      excluded: "地方6県の結果次第",
      order: "保留",
      group: "保留",
    },
  ],
};
